import QtQuick 2.0
import Felgo 3.0

/*

*/

ListPage {
    id:listPage
    section.property: "type"

    // Use a predefined delegate but change some of its layout parameters
    delegate: SimpleRow {
      onSelected: {
        navStack.popAllExceptFirstAndPush(fertigkeitDetailPage, {
                                       modelFertigkeit:item
                                     })
      }
    }

    Component { id: fertigkeitDetailPage;  FertigkeitenDetail { } }

    SectionSelect {
      id: sectionSelect
      anchors.right: parent.right
      target: listPage.listView
      sectionProperty: "gruppe"
    }

    model: [
        { type:"Fertigkeiten", gruppe:"A", beschreibung:"Der Abenteurer beherrscht akrobatische Kunststücke wie Handstand, Überschlag und Salto. Die damit verbundene Körperbeherrschung ist oft hilfreich, zum Beispiel in den folgenden Spielsituationen:
Ein Abenteurer, der zu Boden stürzt, kann noch in derselben Runde aus dem Liegen aufstehen und einen Gegner spontan, d.h. mit einem Abzug von –4, im Nahkampf angreifen, wenn ihm ein EW:Akrobatik gelingt. Springt ein Reiter von seinem laufenden Pferd ab (s. Reiten, S. 121), landet er auf seinen Füßen, wenn ein EW:Akrobatik glückt. In beiden Fällen muss der Abenteurer Akrobatik gelernt haben.\n
Ein ausgebildeter Akrobat kann den Kontrollbereich eines Gegners durchqueren. Er verzichtet dafür in dieser Runde auf eigene Handlungen. Er macht einen Salto über einen Kämpfer hinweg, rollt sich über den Boden unter dem Bauch einer Riesenechse hindurch oder schlägt ein Rad an einem verblüfften Bären vorbei. Gelingt ihm ein EW:Akrobatik, kann der Abenteurer sich in dieser Runde um maximal die Hälfte seiner Bewegungsweite auch durch feindliche Kontrollbereiche hindurch bewegen  bei einem kritischen Erfolg sogar um seine volle Bewegungsweite. Scheitert der EW:Akrobatik, endet die Bewegung im ersten Kontrollbereich, den der Abenteurer betritt. Der Gegner kann ihn dann normal attackieren. Am Ende der Bewegung steht der Akrobat wieder auf seinen Füßen. Nur bei einem kritischen Fehler kommt er nicht auf die Beine und stürzt vor dem ersten Feind zu Boden. Jeder Gegner, dessen Kontrollbereich der Akrobat durchquert und dem  ein WW:Gw/10 gelingt, kann einen spontanen Nahkampfangriff (EW–4:Angriff) versuchen. Dies kostet ihn allerdings eine der Angriffsmöglichkeiten, die ihm in dieser Runde zustehen. Fernkämpfer erleiden gegenüber dem Akrobaten –2 bei ihren Angriffen.\n
Als Teil seiner Ausbildung hat ein Akrobat gelernt, sich bei einem Sprung oder Fall so zu drehen, dass er unverletzt bleibt oder wenigstens so wenig Schaden wie möglich erleidet. Wie gut ihm das gelingt, hängt wesentlich davon ab, ob er absichtlich springt oder nicht. Gelingt ein EW:Akrobatik, wird für die Ermittlung des Sturzschadens nach Tabelle 2 (S. 62) bei einem absichtlichen Sprung die effektive Fallhöhe um 2 m verringert. Stürzt er unabsichtlich, wird die den Schaden bestimmende Fallhöhe nur um 1 m verringert, wenn der Erfolgswurf gelingt. Dies gilt auch für einen unabsichtlichen Sturz vom laufenden Pferd oder vom fahrenden Wagen.\n
Personen, die Akrobatik als ungelernte Fertigkeit einsetzen, können die effektive Fallhöhe bei einem absichtlichen Sprung nur um 1 m verringern. Bei einem ungewollten Fall können sie die Fertigkeit überhaupt nicht einsetzen.\n
Bei einem kritischen Erfolg verringert sich die effektive Fallhöhe zusätzlich um 1 m. Ein kritischer Fehler erhöht den Schaden im Vergleich zu einem normalen Sturz; die effektive Fallhöhe wird um 1 m vergrößert.Springt ein Abenteurer aus großer Höhe absichtlich in ausreichend tiefes Wasser und gelingt ihm ein EW:Akrobatik, verringert sich die effektive Fallhöhe um 15 m (um 12 m beim Einsatz der ungelernten Fertigkeit). Misslingt der Wurf, wird die Fallhöhe wie bei einem ungewollten Sturz nur um 4W3 Meter reduziert.", ungelernt: "+6", kategorie: "Halbwelt, Körperbeherrschung", text: "Akrobatik"},
        { type:"Fertigkeiten", gruppe:"A",  beschreibung:"Alchimie ist die Lehre von den Stoffen, aus denen die Welt zusammengesetzt ist, und von den magischen Essenzen, die man aus ihnen gewinnen kann. Der Alchimist besitzt einfache Kenntnisse über die Eigenschaften von in der Natur vorkommenden Substanzen und über mögliche chemische Reaktionen. Er kann insbesondere auch Gifte, Zaubertrünke und Zaubermittel untersuchen und identifizieren.\n
Um ein Gift, einen Zaubertrunk oder ein anderes Zaubermittel zu analysieren, muss der Alchimist Zugang zu einem Labor haben. Magiergilden in großen Städten verfügen oft über entsprechende Räumlichkeiten, die Mitglieder kostenlos und durchreisende Zauberer gegen eine Gebühr benutzen dürfen. Jede Analyse dauert 2 Stunden. Dabei werden unabhängig vom Erfolg oder Misserfolg Materialien im Wert von 20 GS verbraucht. Der Spielleiter würfelt verdeckt einen EW:Alchimie. Misslingt der Wurf, erhält der Alchimist keine Informationen. Für weitere 20 GS kann er die Untersuchung aber fortsetzen. Bei einem kritischen Fehler täuscht er sich, und der Spieler erhält fehlerhafte Informationen.\n
Ein EW:Alchimie entscheidet auch darüber, ob der Abenteurer ein Gegengift zu einem bekannten Gift kennt. Er weiß dann auch, wie er es herstellen kann, wenn dies nötig sein sollte. Er ist auch in der Lage, selbst das Gegengift zu mischen, wenn er alle Zutaten hat. Der Zeitaufwand hängt von der Art der Herstellung ab und kann zwischen wenigen Minuten und mehreren Stunden oder gar Tagen variieren.
", ungelernt: "0", kategorie: "Wissen", text: "Alchimie" },
        { type:"Fertigkeiten", gruppe:"A", beschreibung:"Wer Anführen beherrscht, kann eine Gruppe von Abenteurern oder eine militärische Einheit geschickt im Kampf einsetzen. Er hat einen geübten Blick für Konfliktsituationen, durchschaut im Kampfgetümmel leichter gegnerische Absichten und kann für die eigene Partei einen Vorteil herausschlagen. Er hat dementsprechend höhere Chancen, die Initiative zu gewinnen (s. S. 59). Es kann vorkommen, dass mehrere Personen einer Partei im Anführen ausgebildet sind. Dann übernimmt derjenige mit dem höchsten Fertigkeitswert die Führung, solange er in der Lage ist, seinen Gefährten Anweisungen zu geben.\n
Anführen wird auch von Kapitänen großer Schiffe eingesetzt, um ihre Mannschaft in Notsituationen und im Kampf zu koordinieren. EW:Anführen der Kapitäne oder bei kleineren Schiffen der Bootsführer entscheiden bei Seegefechten, wer die Initiative gewinnt.\n
Allgemein kann Anführen in Spielsituationen nützlich sein, die aufeinander abgestimmtes Zusammenarbeiten einer Gruppe erfordern. Der Spielleiter kann hierbei den erfolgreichen Einsatz von Anführen durch Zuschläge bei Erfolgswürfen für andere Fertigkeiten belohnen.\n
Menschen, Elfen, Gnome, Halblinge und Zwerge haben den ungelernten Fertigkeitswert von +(6) für Anführen. Alle andere Geschöpfe Midgards beherrschen die Fertigkeit mit einem Zehntel (abgerundet) ihrer artspezifischen Intelligenz, maximal aber mit +(6).", ungelernt: "+6", kategorie: "Kampf, Sozial", text: "Anführen" },
        { type:"Fertigkeiten", gruppe:"A", beschreibung:"Der Athlet hat seine Muskulatur durch mühsames Krafttraining aufgebaut. Dadurch sieht er besser aus, und er hat gelernt, seine Körperkraft bei kurzzeitigen Anstrengungen effektiver einzusetzen. Das Aussehen eines Abenteurers erhöht sich um seinen durch 3 geteilten (und abgerundeten) Fertigkeitswert in Athletik, wobei der Maximalwert 100 aber nicht überschritten werden kann.\n
Gelingt ein EW:Athletik, kann ein Abenteurer größere Gewichte stemmen oder schieben als gleichstarke normale Menschen. Er hat allerdings nur einen Versuch. Dann steigt seine Höchstlast um 10 kg, seine Schublast um 20 kg (s. Tabelle 1, S. 59). Seine Traglast ändert sich jedoch nicht, da Athletik nichts beim Tragen von großen Gewichten über einen längeren Zeitraum nützt.\n
Scheitert ein Abenteurer, der Athletik gelernt hat, bei einem PW:Stärke, hat er eine zweite Chance. Gelingt ihm ein EW:Athletik, darf er anschließend den Prüfwurf wiederholen, und das günstigere Ergebnis der beiden Prüfwürfe zählt. Diese Regel der zweiten Chance gilt auch für Kraftakte. Bei einem kritischen Erfolg braucht der zweite Prüfwurf nicht mehr gewürfelt zu werden. Der Abenteurer hat auf jeden Fall Erfolg beim Einsatz seiner rohen Kraft.Wenn zwei Abenteurer in einem Wettbewerb, zum Beispiel beim Armdrücken, ihre Kräfte messen, kann dies durch Erfolgsund Widerstandswürfe mit Fertigkeitswert Stärke/10 geregelt werden (s. S. 51). In einem solchen Fall darf ein Abenteurer anstelle des EW:Stärke/10 einen EW:Athletik würfeln, wenn dies für ihn günstiger ist. Entsprechendes gilt für Widerstandswürfe.\n
Unterläuft einem Abenteurer beim EW:Athletik ein kritischer Fehler, zerrt er sich einen Muskel. Er verliert 1W6 AP und kann 2W6 Tage lang keine Fertigkeiten einsetzen, bei denen Stärke die Leiteigenschaft ist. Ein so verletzter Abenteurer kann auch keine Kraftakte mehr machen und darf maximal seine Normallast (s. Tabelle 1) tragen, heben oder schieben.", ungelernt: "0", kategorie: "Kampf, Körperbeherrschung", text: "Athletik" },
        { type:"Fertigkeiten", gruppe:"B", beschreibung:"Um freihändig über schmale Stege, auf schrägen Dächern und an anderen Orten zu laufen, wo normale Menschen leicht das Gleichgewicht verlieren, muss ein Abenteurer sein Geschick im Balancieren einsetzen. Erfolgswürfe sind erst dann nötig, wenn die Lauffläche höchstens 20 cm breit oder mindestens 30 Grad geneigt ist. Ein Abenteurer bewegt sich unter diesen Umständen höchstens mit B6. Ist die Lauffläche höchstens 10 cm breit oder mindestens 40 Grad geneigt, bewegt er sich nur noch mit B3. Wenn er ein größeres Risiko eingehen will, kann er auch schneller laufen.\n
Ein balancierender Abenteurer muss in jeder Runde (alle 10 sec) einen Erfolgswurf machen. Bei kritischem Erfolg darf er sich mit doppelter Geschwindigkeit bewegen. Scheitert der Wurf auf normale Weise, entscheidet ein zweiter EW:Balancieren über die Folgen. Gelingt der Wurf, hat der Abenteurer rechtzeitig gemerkt, dass er zu fallen droht. Er bleibt stehen und verbringt die Runde damit, wieder sein Gleichgewicht zu erlangen. Misslingt der zweite Erfolgswurf oder war schon der erste Wurf ein kritischer Fehler, stolpert der Abenteurer oder rutscht aus. Er hat dann aber oft noch die Möglichkeit, sich an der Laufplanke, an der Dachkante oder an einem Seil festzuhalten, bevor er abstürzt. Darüber entscheidet ein PW:Gw/2 mit Zuschlägen oder Abzügen, die  der Spielleiter je nach Situation festlegen kann. Gelingt dieser Prüfwurf, verliert der Abenteurer durch die Anstrengung 1W6 AP.\n
Balancieren hilft auch, wenn ein Abenteurer sich auf einer schaukelnden Hängebrücke, einem dahinrasenden Wagen, an Bord eines Schiffs in stürmischer See oder auf einem fliegenden Teppich aufhält und auf dem stark schwankenden Untergrund agieren will. Hier entscheidet ein EW:Balancieren, ob er eine Handlung überhaupt ausführen oder Nachteile, zum Beispiel Abzüge bei EW:Angriff, vermeiden kann.\n
Schwierigkeit beim Einsatz von Balancieren\n
sehr leicht (+4)
Abenteurer benutzt wenigstens 2 m lange Balancierstange\n
schwer (–2)
Lauffläche ist schmal (etwa 15 cm), schräg (etwa 35 Grad Neigung) oder rutschig\n
sehr schwer (–4)
- Lauffläche ist sehr schmal (etwa 10 cm), sehr schräg (etwa 40 Grad Neigung) oder sehr rutschig
- Abenteurer trägt Plattenoder Vollrüstung oder schwere Last (s. Tabelle 1)
- Abenteurer bewegt sich mit doppelter Geschwindigkeit als beim Balancieren üblich
starke Windböen\n
besonders schwer (–6)
Lauffläche ist extrem schmal (etwa 5 cm) oder extrem schräg (45 Grad Neigung)\n
äußerst schwer (–8)
Balancieren auf einem Seil\n
Abenteurer bewegt sich mit vierfacher Geschwindigkeit als beim Balancieren üblich", ungelernt: "+6", kategorie: "Halbwelt, Körperbeherrschung", text: "Balancieren" },
        { type:"Fertigkeiten", gruppe:"B", beschreibung:"Der im beidhändigen Kampf ausgebildete Abenteurer kann in jeder Hand eine Nahkampfwaffe führen. Die beiden Waffen kann er nach Belieben aus den Einhandschwertern, Stichwaffen und Einhandschlagwaffen wählen. Die Fertigkeitswerte, mit denen er die benutzten Waffen beherrscht, müssen mindestens so hoch sein wie sein Fertigkeitswert im beidhändigen Kampf.Der beidhändig kämpfende Abenteurer kann sich in jeder Runde für eine von drei Angriffsmöglichkeiten entscheiden.\n
- Er kann mit der Waffe, die er in seiner Waffenhand hält, angreifen und die andere Waffe nicht einsetzen. Dies ist ein normaler Angriff, der mit einem Erfolgswurf für die Waffenfertigkeit entschieden wird.\n
- Er kann mit beiden Waffen getrennt eine oder zwei verschiedene Personen attackieren. Ob er trifft, wird mit zwei EW:beidhändiger Kampf entschieden; bei Treffern entscheidet jeweils ein WW:Abwehr des Gegners, ob die Waffe leichten oder schweren Schaden anrichtet.\n
- Er kann einen Kombinationsangriff mit beiden Waffen gegen denselben Gegner führen. Der Kämpfer versucht so, einen hohen Rüstungsschutz zu überwinden, indem er mit Wucht beide Klingen kurz hintereinander auf denselben Punkt aufschlagen lässt. Bei dieser Kampftechnik wird nur ein EW:beidhändiger Kampf gewürfelt, gegen den der Gegner sich mit einem WW:Abwehr wehrt. Der angerichtete Schaden ist die Summe der Schadenswirkungen beider Waffen.\n
Bei Angriffen mit beidhändigem Kampf werden alle situationsbedingten Zuschläge und Abzüge für Angriffe angerechnet. Der Schadensbonus des Angreifers wird nur einmal berücksichtigt, und zwar bei der in der Haupthand gehaltenen Waffe. Beidhändige Abenteurer (s. S. 34) dürfen auswählen, welchen Hieb sie mit mehr Wucht führen. Der magische Angriffsoder Schadensbonus der benutzten Waffen wird jeweils einzeln berücksichtigt. Kritische Erfolge und Fehler bei EW:Beidhändiger Kampf haben dieselben Auswirkungen wie bei normalen EW:Angriff.
", ungelernt: "0", kategorie: "Kampf", text: "Beidhändiger Kampf" },
        { type:"Fertigkeiten", gruppe:"B", beschreibung:"Mit Beredsamkeit kann ein Abenteurer seinen Gesprächspartner emotional vom eigenen Standpunkt überzeugen, für sich einnehmen oder zu einer Handlung überreden. Ein erfolgreicher Einsatz der Fähigkeit erweckt bei dem Gegenüber den Eindruck, dass es sich bei dem zungenfertigen Abenteurer um einen sympathischen Menschen handele, dem man einfach Glauben schenken und helfen müsse. Beredsamkeit wird daher oft benutzt, um beim ersten Kontakt mit einem Fremden „das Eis zu brechen.“ Gegen diesen Einsatz des Redetalents hat niemand etwas einzuwenden.\n
Wird Beredsamkeit dagegen benutzt, um andere Personen zu etwas zu überreden, was ihren Grundüberzeugungen oder ihrem Eigeninteresse zuwiderläuft, dann steht ihnen ein Widerstandswurf für Menschenkenntnis oder auch für Beredsamkeit zu. Der Gesprächspartner kann so merken, dass er mit kunstvollen, aber leeren Worten abgespeist wird, und reagiert eventuell beleidigt oder verärgert.\n
Beredsamkeit lässt sich auch bei Ansprachen an größere Menschenmengen einsetzen, die beeindruckt, angestachelt oder beruhigt werden sollen. Allerdings können die Folgen von Fehlern bei der Rede handfestere Formen als bloßes Ignorieren oder Ausbuhen annehmen von faulem Obst bis zu massiven Mauersteinen. Auch einer Menschenmenge steht ein Widerstandswurf zu; wie bei unbedeutenden Passanten kann der Spielleiter hierfür den ungelernten Fertigkeitswert für Menschenkenntnis benutzen. Er kann ihn aber auch niedriger ansetzen, da Menschenmassen oft leichter emotional zu beeinflussen sind als Einzelpersonen.\n
Will ein Abenteurer eine Geschichte spannend und dramatisch erzählen, um die Aufmerksamkeit seiner Zuhörer zu fesseln oder sie zu beeindrucken, wird der Erfolg ebenfalls mit einem EW:Beredsamkeit entschieden. Will der Erzähler seine Zuhörer ganz in seinen Bann ziehen, um sie von heimlichen Aktivitäten seiner Gefährten abzulenken, wird das wie ein vergleichbarer Einsatz von Musizieren geregelt (s. S. 119).", ungelernt: "+3", kategorie: "Sozial", text: "Beredsamkeit" },
        { type:"Fertigkeiten", gruppe:"B", beschreibung:"Der Abenteurer kann ein ahnungsloses Opfer mit einem Hieb bewusstlos schlagen, wenn er sich ihm unbemerkt nähern kann - zum Beispiel, weil er von hinten heranschleichen konnte oder weil das Opfer schläft. Beim Betäuben benutzt der Angreifer seine Faust, einen Schlagring (s. S. 142), eine kleine Keule oder einen mit Sand gefüllten Lederbeutel.
Sobald sein Opfer in Reichweite ist, würfelt der Abenteurer zuerst einen EW:Angriff für Faustkampf (mit oder ohne Schlagring), für Einhandschlagwaffen (Keule, Lederbeutel) oder mit dem ungelernten Fertigkeitswert +(4) für bloße Hand und improvisierte Waffen. Da der Gegner wehrlos ist, erhält der Angreifer einen Zuschlag von +4. Ein Treffer richtet nur leichten Schaden an. Nur bei kritischem Erfolg verursacht der Hieb eine schwere Verletzung am Kopf (s. S. 63f).
War der Angriff erfolgreich, folgt ein EW:Betäuben. Erfahrene Personen von hohem Grad haben bessere Reflexe als normale Menschen oder sind vom Glück begünstigt. Daher wirkt der der durch 3 geteilte und abgerundete Grad des Opfers als Abzug auf den Erfolgswurf. Gelingt der EW– (Grad/3):Betäuben, ist der Getroffene mehrere Minuten lang bewusstlos. Andernfalls hat er im letzten Moment etwas gespürt und konnte der vollen Wucht des Schlags entgehen.
Der Schlag oder das Zusammensacken eines stehenden Opfers verursachen eventuell Geräusche. Halten sich aufmerksame Kameraden des Opfers in der Nähe auf, kann ein EW:Schleichen entscheiden, ob sie aufmerksam werden.
    ", ungelernt: "+6", kategorie: "Halbwelt, Kampf", text: "Betäuben" },
        { type:"Fertigkeiten", beschreibung:"Diese Fertigkeit befähigt den Abenteurer, mit einem Steuerruder Ruderboote oder kleine Segelboote zu lenken. Er kann auch geschickt mit kleinen Ruderbooten, Kanus, Kajaks, Einbäumen und anderen Wasserfahrzeugen umgehen, die mit Rudern oder Paddeln gesteuert werden. Ein Erfolgswurf ist nur in außergewöhnlichen Situationen nötig, z.B. wenn das Boot in Stromschnellen oder in ein Unwetter gerät, einem plötzlich auftauchenden Hindernis ausweichen oder gegen eine starke Strömung ankämpfen muss oder wenn ein großes Tier das Gefährt rammt. Bei Misserfolg misslingt das Manöver, und das Boot kann in Schwierigkeiten geraten. Unter besonders ungünstigen Umständen kann es sogar kentern - z.B. wenn ein Rettungsboot in Gefahr gerät, von dem sinkenden Mutterschiff mit in die Tiefe gerissen zu werden oder wenn ein Segler in einem schweren Sturm versucht, den sicheren  Hafen zu erreichen. Bei einem kritischen Fehler besteht auf jeden Fall die Gefahr, dass das Boot umkippt, wenn das misslungene Manöver oder der Seegang das Kentern möglich erscheinen lassen. Gerät ein Boot mit mehreren Abenteurern, die Bootfahren beherrschen, in eine gefährliche Situation, muss nur der Fähigste einen Erfolgswurf ausführen.\n
Ein im Bootfahren geschulter Abenteurer kann alleine ein kleines Segelboot (bis zu 6 m Rumpflänge) steuern. Auf größeren Segelbooten (bis 10 m Rumpflänge) benötigt er außerdem einen oder mehrere Hilfsmatrosen. Mit Bootfahren kann man auch auf großen Segel- oder Ruderschiffen das Steuer übernehmen. Dort muss allerdings zusätzlich ein im Anführen geschulter Kapitän die Arbeit des Steuermanns und der Matrosen koordinieren
", gruppe:"B", ungelernt: "+3", kategorie: "Alltag", text: "Bootfahren" },
        { type:"Fertigkeiten", beschreibung:"Erste Hilfe nützt dem Abenteurer, der durch äußere Verletzungen (Kämpfe, Stürze, Feuer usw.) Lebenspunkte verloren hat. Wer Erste Hilfe gelernt hat, kann fachmännisch Wunden verbinden, Blutungen stoppen und Brüche schienen.
Ein verletzter Abenteurer erhält durch die geübte Versorgung seiner Wunden 1W6 LP & AP zurück, wenn der EW:Erste Hilfe gelingt. Bei einem kritischen Erfolg werden 1W6+2 LP & AP geheilt. Misslingt der Erfolgswurf, ändert sich am Zustand des Behandelten nichts; bei einem kritischen Fehler verliert er 1W6–3 LP & AP. Ein Verwundeter erhält durch Erste Hilfe immer genau so viele AP wie LP zurück, auch wenn dank Rüstungsschutz seine LP-Verluste geringer als die Ausdauerverluste waren.\n
Erste Hilfe kann immer dann eingesetzt werden, wenn ein Abenteurer in einer zusammenhängenden Spielsituation (Kampf, Unfall, Flucht aus brennendem Haus usw.) verletzt worden ist. Dabei spielt es keine Rolle, ob der Schaden auf einmal oder - z.B. im Kampf nach mehreren Treffern - mit verschiedenen Würfen ausgewürfelt worden ist. Durch Erste Hilfe kann ein Verwundeter nicht mehr LP zurückgewinnen, als er in der zusammenhängenden Situation verloren hat, in der er seine Verletzungen erlitten hat.\n
Ein Abenteurer, der auch Heilkunde beherrscht, kann seine Erfolgschancen bei der Anwendung von Erster Hilfe verbessern. Gelingt ein EW:Heilkunde, kann der Anwender entweder\n
- +4 auf seinen EW:Erste Hilfe bekommen;\n
- oder zusätzlich +1 LP & AP heilen, wenn der EW:Erste
Hilfe gelingt.\n
Die Erstversorgung eines Verletzten dauert 10 min. Jeder Ersthelfer kann nur einmal versuchen, die Schäden eines Verwundeten zu lindern. Gelingt sein EW:Erste Hilfe, kann sich kein zweiter Abenteurer mit dieser Fertigkeit um den Verletzten kümmern. Die Wunde ist fachmännisch versorgt worden, und wenn dem Verwundeten noch Lebenspunkte fehlen, dann war nicht mehr zu machen. Scheitert aber der Erfolgswurf, können andere Personen dem Verletzten Erste Hilfe leisten. Wegen der verstrichenen Zeit ist die Wundversorgung aber nur noch eingeschränkt möglich: Der Behandelte erhält bei Erfolg nur 1W3 LP & AP zurück und bei kritischem Erfolg 1W3+1.  Ein Abenteurer kann Erste Hilfe auch auf sich selbst anwenden, wenn er bei Bewusstsein, in seinen Bewegungen nicht zu sehr eingeschränkt ist und die Wunde bequem erreicht. Das Schienen des eigenen gebrochenen Armes oder die Versorgung einer Rückenwunde ist z.B. nicht möglich.\n
Wer Erste Hilfe beherrscht, kann auch in geringem Maße Vergiftungen behandeln, wenn das Gift langsam genug wirkt und einfach aus dem Körper entfernt werden kann, bevor es den vollen Schaden anrichtet (s. »Behandlung von Vergiftungen«, S. 67). Der geschulte Abenteurer weiß, wie man eine Schlangenbisswunde aussaugt oder wie man jemanden, der vergiftetes Fleisch gegessen hat, zum Erbrechen bringt. Erste Hilfe nützt auch bei Verstauchungen (s. Geländelauf, S. 112) und bei der Behandlung vor dem Ertrinken geretteter Abenteurer (s. Tauchen, S. 130).\n
Um Erste Hilfe anwenden zu können, braucht ein Abenteurer Salben, Heilkräuter und Verbände, die ihn zusammen 30 GS kosten. Alle zwei Monate muss diese Ausrüstung für 20 GS ergänzt werden, denn Heilmittel werden verbraucht oder sind nur begrenzt haltbar.", gruppe:"E", ungelernt: "+0", kategorie: "Alltag", text: "Erste Hilfe" },
        { type:"Fertigkeiten", beschreibung:"Ein Abenteurer, der Etikette beherrscht, ist mit der Lebens- und Verhaltensweise des Adels und der gutbürgerlichen Kreise seiner Heimat vertraut. Er weiß, wie er sich verhalten muss, um kein Missfallen zu erregen. In anderen Ländern sind eher Erfolgswürfe nötig. Außerdem werden dort EW:Etikette mit umso größeren Abzügen erschwert werden, je fremdartiger die Sitten und die Gesellschaftsform des Landes sind. Solche Nachteile können abgemildert werden, wenn vorher Landeskunde erfolgreich eingesetzt wird.\n
In seiner Heimat muss der Abenteurer im normalen Umgang mit hochgestellten Personen keine Erfolgswürfe würfeln. Er versteht es, sich in Gesellschaft zu benehmen und mit einflussreichen und mächtigen Personen zu verkehren, ohne unangenehm aufzufallen. Er weiß, welchen Würdenträger er wie anreden muss, wann ein Handkuss oder ein Kniefall angebracht ist usw. Er besitzt auch in den besseren Kreisen übliches Wissen, z.B. über den Aufbau des Haushalts eines reichen Händlers oder eines Landadligen.\n
Erfolgswürfe sind dann nötig, wenn der Abenteurer etwas Besonderes erreichen möchte:\n
- eine besondere Gunst wie die Finanzierung einer Schatzsuche durch einen reichen Gönner,\n
- eine besondere Information wie den Namen und die Schwächen der neuesten Favoritin des Barons,\n
- die Beschwichtigung eines Dieners, der einen in einem Zimmer seines Herrn erwischt hat, wo man wirklich nichts zu suchen hatte,\n
- ein überzeugendes Auftreten vor einem zu Gericht sitzenden Landadligen, der gar nicht erst auf die Idee kommen soll, man hätte etwas mit einem schnöden Diebstahl zu tun.\n
EW:Etikette können auch erforderlich oder in Form von Zuschlägen hilfreich sein, wenn jemand andere soziale Fertigkeiten wie Beredsamkeit, Verführen oder Verstellen einsetzt und die Zielpersonen den besseren Kreisen angehören.\n
Bei der Suche nach Unterstützung oder Informationen hat ein misslungener Erfolgswurf keine schlimmen Auswirkungen; man hält den Abenteurer schlimmstenfalls für einen Emporkömmling oder Langweiler. Ein kritischer Fehler bedeutet allerdings, dass die Anwesenden ernstlich schockiert und längerfristig verärgert sind.\n
Teil der Etikette sind auch Grundkenntnisse der Aktivitäten, mit denen sich die Wohlhabenden ihre Zeit vertreiben. Hierzu gehören die Regeln von Brettspielen oder die Schrittfolgen von Tänzen, die in der Heimat des Abenteurers populär sind. Ähnliche Spiele und Tänze in anderen Ländern lernt der Abenteurer schnell.", gruppe:"E", ungelernt: "+0", kategorie: "Alltag, Sozial", text: "Etikette" },
        { type:"Fertigkeiten", beschreibung:"Mit dieser Fertigkeit können Dokumente, Siegel, Prägestöcke und Unterschriften gefälscht werden. Der Fälscher braucht verschiedene Hilfsmittel und Werkzeuge, die einmlig 200 GS kosten. Fehlt diese Ausrüstung und improvisiert der Abenteurer mit dem, was er gerade zur Hand hat, steigt die Gefahr, dass die Fälschung entdeckt wird. Wie lange die Arbeit des Fälschers dauert, hängt sehr davon ab, was er nachahmen will. Eine kurze Notiz mit einer gefälschten Unterschrift dauert wenige Minuten, während die Herstellung eines komplizierten Siegels mit Urkundenband mehrere Tage in Anspruch nehmen kann. Entsprechend variabel sind die Zusatzkosten (teures Pergament, spezielle Tinte und Siegel wachs, edle Metalle usw.). Der Fälscher kann auch Münzen, Siegelringe, Ordensabzeichen und andere Gegenstände aus Metall nachahmen. Dazu braucht er aber eine gut ausgestattete Fälscherwerkstatt.\n
Für eine Kopie muss der Fälscher mindestens eine Stunde lang das Original zur Verfügung haben. In dieser Zeitspanne kann er sich die wesentlichen Merkmale des Dokuments oder der Unterschrift einprägen. Kann er nur einen kurzen Blick auf das Original werfen, verschlechtern sich seine Erfolgsaussichten wesentlich, außer er besitzt die angeborene Fähigkeit Einprägen und setzt sie erfolgreich ein. Fälscht ein Abenteurer ein Dokument mit einem längeren Text, den er selbst formuliert hat, kann der Spielleiter je nach Art des Schriftstücks mit Erfolgswürfen für Sprechen oder Schreiben entscheiden, ob der Schreibstil angemessen und die Rechtschreibung fehlerfrei ist.\n
Ein EW:Fälschen wird nach Fertigstellung der Fälschung verdeckt vom Spielleiter gewürfelt, der bei Erfolg oder kritischem Scheitern das Gesamtresultat in seinen Unterlagen notieren muss. Gelingt der Erfolgswurf, sieht das Dokument bei oberflächlicher Betrachtung echt aus. Für eine routinemäßige Passkontrolle auf kanthanischen Landstraßen oder einen kurzen Blick auf einen Frachtbrief in chryseischen Häfen reicht das aus. Scheitert der Erfolgswurf, merkt der Fälscher, dass sein Werk misslungen ist. Er hat dann nur Zeit und das eingesetzte Material verloren. Bei einem kritischen Fehler scheint die Fälschung auf den ersten Blick gelungen, wird aber beim ersten Einsatz sofort erkannt.\n
Wird das gefälschte Objekt später eingehend auf seine Echtheit untersucht, steht dem Betrachter ein Widerstandswurf für eine passende Fähigkeit zu, z.B. Landeskunde bei Dokumenten oder Geld, Schätzen bei gefälschtem Schmuck, Zauberkunde bei gefälschten magischen Artefakten oder auch für Fälschen, Wahrnehmung oder In/10, je nachdem, was passt und was bei mehreren Alternativen erfolgsversprechender ist.\n
Schwierigkeit beim Einsatz von Fälschen\n
leicht (+2)
Fälscher besitzt das Original oder ein ähnliches Vorbild und kann sich beliebig Zeit lassen\n\n
schwer (–2)
Fälschen eines offiziellen Dokuments (Pass, Handelserlaubnis, ...)
Fälschen unter großem Zeitdruck\n
sehr schwer (–4)
Fälschen eines Siegels\n
besonders schwer (–6)
Fälscher benutzt improvisiertes Werkzeug oder Material\n
äußerst schwer (–8)
Fälscher hat das Original nie gesehen
Schwierigkeit beim Widerstand gegen Fälschen\n
besonders leicht (+6)
Betrachter ist mit dem Original (Unterschrift, Siegel, etc.) sehr vertraut\n
sehr leicht (+4)
Betrachter vermutet bereits eine Fälschung\n
leicht (+2)
Betrachter ist allgemein misstrauisch\n
schwer (–2)
Betrachter ist vertrauensselig\n
sehr schwer (–4)
Betrachter ist vertrauensselig und wird bei der Untersuchung abgelenkt", gruppe:"F", ungelernt: "+0", kategorie: "Halbwelt", text: "Fälschen" },
        { type:"Fertigkeiten", beschreibung:"Der Blick des Abenteurers ist geschult, schwache Hinweise auf mechanische Fallen, wie man sie in Gebäuden antrifft, zu erkennen. Er weiß, wo er hinschauen muss, um derartige Vorrichtungen rechtzeitig zu entdecken z.B. Stolperdrähte, die Armbrust- und Speerfallen auslösen, lose Bodenplatten, die bei Belastung ein Fallgitter heruntersausen lassen, oder den unscheinbaren Giftdorn, der einen Türknauf sichert. Der Abenteurer hat auch einen Blick für instabile Wände, Säulen und Stützbalken oder einsturzgefährdete Decken, Treppen und Böden. Er kann beurteilen, ob ein schmaler Weg entlang eines Abgrunds sicher ist, ob an einem Abhang Steinschlaggefahr besteht und wie viel Gewicht eine baufällige Brücke aushält. Zusätzlich weiß er, wie gängige Zauberfallen an magischen Zeichen erkannt werden können, die in Ornamenten oder Bildern an Wänden, Türen oder Gegenständen verborgen sein können.\n
Sucht ein Abenteurer an einer ihm verdächtig erscheinenden Stelle, z.B. einer außergewöhnlichen Tür oder Truhe, sorgfältig nach Fallen, braucht er dafür 10 min. Steht ihm weniger Zeit zur Verfügung, wird der Erfolgswurf durch Abzüge erschwert, die der Spielleiter je nach Situation verhängt.  Mehrere Personen können nicht gleichzeitig am selben Ort suchen. Der EW:Fallen entdecken wird vom Spielleiter verdeckt gewürfelt. Bei einem kritischen Fehler löst der Suchende bei seinen Bemühungen versehentlich die Falle aus. Bei Erfolg entdeckt er nicht nur die Falle, sondern er hat auch eine ungefähre Vorstellung von ihrer Wirkungsweise. Einem in die Wand führenden Stolperdraht sieht er aber nicht an, welche mechanische Vorrichtung durch ihn ausgelöst wird, und seltsam aussehende magische Zeichen sagen höchstens dem in Zauberkunde geschulten Abenteurer mehr, als dass sie gefährlich sein könnten.\n
Der Abenteurer kann eine Falle oder andere der genannten Gefahren automatisch entdecken, wenn er sich ihr auf 2 m nähert und wenn die sichtbaren Bestandteile mindestens 10 cm lang sind (also verborgene Fallgitter, die aus einem entsprechend langen Schlitz in der Decke herunterfallen, aber keine 1 cm langen Giftdorne oder Schutzrunen). Die mangelnde Stabilität eines Bauwerks fällt bereits automatisch auf, wenn der Abenteurer sich der kritischen Stelle auf 15 m nähert.
", gruppe:"F", ungelernt: "+0", kategorie: "Unterwelt", text: "Fallen entdecken" },
        { type:"Fertigkeiten", beschreibung:"Der Abenteurer hat sich ausgiebig mit mechanischen Fallen beschäftigt, wie man sie in Gebäuden antrifft. Dazu gehören zum Beispiel Stolperdrähte, getarnte Falltüren, Armbrustund Speerfallen, Giftdornen, bei Tritt auf Bodenplatten aus der Wand hervorklappende Sensenblätter oder Mechanismen, die gasgefüllte Glaskugeln zerbrechen. Mit Fallenmechanik kann man solche Vorrichtungen unschädlich machen, wenn man sie erst einmal entdeckt hat. Ein Versuch dauert in der Regel 10 min. Bei einem kritischen Fehler wird die Falle beim Entschärfen versehentlich ausgelöst, und der Abenteurer erleidet den vollen Schaden. Bei ungewöhnlichen Fallen kann der Spielleiter die Erfolgschancen durch Abzüge und Zuschläge auf den EW:Fallenmechanik beeinflussen.\n
Der in Fallenmechanik geschulte Abenteurer kann mit einfachen Hilfsmitteln innerhalb von 10 min selbst Fallen improvisieren. Der Spieler muss eine vernünftige Beschreibung der Wirkungsweise und Konstruktion liefern. Der Spielleiter entscheidet mit einem verdeckten Erfolgswurf, ob die Falle funktionieren wird. Bei einem kritischen Fehler löst der Fallenbauer die Falle bereits beim Aufbau aus. Bei improvisierten Fallen muss allerdings ein zweiter Erfolgswurf gemacht werden, bevor ein Opfer in die Falle geht. Misslingt dieser Erfolgswurf, ist die Falle nicht gut genug getarnt und wird vorzeitig von dem sich nähernden Wesen bemerkt. \n
Fallenmechanik beinhaltet auch das Wissen um die Bedienung und Reparatur anderer feinmechanischer Geräte, die man auf der Welt Midgard vorfinden kann. Dazu gehören auch die gängigen Geheimmechanismen, mit denen verborgene Türen geöffnet werden können. Wenn ein Abenteurer von der Existenz einer solchen Vorrichtung weiß, dann kann er sie mit einem EW:Fallenmechanik finden und bedienen.\n
Bedienen von Geheimmechanismen
Ist ein Abenteurer über die Existenz einer Geheimtür, eines Geheimfachs oder einen anderen verborgenen Vorrichtung informiert, zum Beispiel durch Einsatz von Spurensuche oder durch Belauschen von Nichtspielerfiguren, weiß er noch nicht, wie sie sich öffnen oder bedienen lässt.\n
Geheimmechanismen werden oft über einen verborgenen Druckknopf, einen winzigen Hebel, einen geringfügig vorstehenden Mauerstein, ein bewegliches Mosaiksteinchen oder eine ähnlich unscheinbare Vorrichtung betätigt. Abenteurer können sie mit EW:Fallenmechanik oder auch mit EW:Spurensuche finden. Das Absuchen eines 1 Quadratmeter großen Bereichs dauert 1 min. Findet ein Abenteurer nichts, dürfen seine Gefährten anschließend ihr Können an derselben Stelle erproben.\n
Manche Geheimtüren öffnen sich einfach, wenn man nur fest gegen sie drückt. In einem solchen Fall muss nicht gewürfelt werden, wenn ein Abenteurer an der richtigen Stelle gegen die Wand drückt. Wenn die Spieler nicht von allein auf diese Idee kommen, können sie die nötige Information aber auch über geglückte Erfolgswürfe für Fallenmechanik oder Spurensuche erhalten.\n
Der Spielleiter kann auch besondere Öffnungsmechanismen entwerfen, die die Spieler nur durch Nachdenken und durch gezielte Handlungen finden können. Zum Beispiel könnte eine Geheimtür sich öffnen, wenn im Nachbarraum der Arm einer Statue als Hebel betätigt wird. In der Nähe der Tür ist die Suche nach dem Öffnungsmechanismus dadurch auf jeden Fall zum Scheitern verurteilt. Entdeckt ein Abenteurer durch Herumprobieren, dass sich der Arm der Statue nach unten drücken lässt, öffnet sich die Tür automatisch, selbst wenn sie vorher noch nicht entdeckt worden ist. Es ist aber auch möglich, die Statue mit Fallenmechanik oder Spurensuche zu untersuchen. Der Abenteurer, der so das unscheinbare Scharnier entdeckt, weiß allerdings nicht, was passiert, wenn er den Arm bewegt.", gruppe:"F", ungelernt: "-", kategorie: "Unterwelt", text: "Fallenmechanik" },
        { type:"Fertigkeiten", beschreibung:"Beim Fechten gelingt es dem Abenteurer, durch Körperhaltung und Stellung dem Gegner immer die Spitze seiner Waffe entgegenzuhalten. Auf diese Weise hat er mehr Möglichkeiten zum Zustechen oder auch zum Parieren.\n
Die Fechtkunst entstand auf Midgard erst in jüngster Zeit und ist nur innerhalb des Valianischen Imperiums und der Küstenstaaten bekannt. Lehrmeister für diese Fähigkeit finden Aben- teurer daher auch nur in diesen Ländern, und nur dort gibt es eine große Auswahl an Fechtwaffen zu kaufen.\n
Ein Abenteurer benutzt zum Fechten eine Fechtwaffe, die er mit mindestens demselben Fertigkeitswert wie Fechten beherrschen muss. In der anderen Hand kann er einen Parierdolch, einen Buckler oder einen kleinen Schild führen. Zu Beginn jeder Runde (zu 10 sec) muss der Abenteurer sich entscheiden, ob er zusätzlich zu seinem normalen Angriff einen zweiten Angriff oder eine aktive Parade mit der Fechtwaffe ausführen will.\n
Entscheidet sich der Abenteurer für einen zweiten Angriff, würfelt er am Ende der Runde einen EW:Fechten anstelle eines weiteren EW:Angriff mit der Fechtwaffe. Dabei werden dieselben situationsbedingten Zuschläge und Abzüge wie bei normalen Angriffen berücksichtigt. Dem Gegner steht ein WW:Abwehr zu, wenn der EW:Fechten gelingt, und kritische Erfolge und Fehler haben dieselben Auswirkungen wie bei normalen Angriffen. Ein magischer Angriffsoder Schadensbonus der Fechtwaffe wirkt sich auch auf den EW:Fechten aus. Der persönliche Schadensbonus des Angreifers wird allerdings beim zweiten Angriff nicht berücksichtigt.\n
Eine Parade mit der Fechtwaffe nützt dem Fechter nur gegen einen Gegner, den der Spieler bestimmen muss, bevor die EW:Angriff der Runde gewürfelt werden. Erzielt dieser Angreifer einen Treffer, steht dem Fechter ein WW:Fechten zu, bei dessen Gelingen er nur 1 AP verliert. Misslingt der WW:Fechten, steht dem Fechter immer noch sein normaler WW:Abwehr zu. Nur Angriffe mit einhändigen Nahkampfwaffen können mit Fechtwaffen pariert werden. Gegen Angriffe mit zweihändig geführten Waffen und mit natürlichen Waffen wie Biss, Pranke usw. helfen Fechtkenntnisse nicht.", gruppe:"F", ungelernt: "+0", kategorie: "Kampf", text: "Fechten" },
        { type:"Fertigkeiten", beschreibung:"Ein Abenteurer, der über Gassenwissen verfügt, ist mit dem Leben in den Städten Midgards vertraut - auch mit dessen Schattenseiten! Er weiß, wie man zu einer preiswerten Unterkunft kommt, welche Händler aus dem Rahmen des Üblichen fallende Waren anbieten oder ankaufen, in welchen Gesellschaftskreisen man Hilfe und Informationen für bestimmte Probleme findet, wo man sich amüsieren kann, welche Trinkgelder angebracht sind usw. Er findet sich leichter im Straßengewirr einer unbekannten Stadt zurecht, er orientiert sich besser, und er erkennt leichter Passanten, die ihm eine Auskunft geben können. Bei kritischem Erfolg findet der Abenteurer mehr Informationen, mehr Unterstützung oder großzügigere Händler, als er normalerweise erwarten konnte.
Der Abenteurer kennt sich vor allem auch im Milieu der Halbund Unterwelt aus und besitzt Kenntnisse und Erfahrungen, die man in Stadtvierteln sammeln kann, in die sich anständige Bürger nur ausnahmsweise hineintrauen. Dies hilft ihm bei der Kontaktaufnahme mit kriminellen Elementen, beim Anheuern von Personen, die auch vor illegalen Unternehmungen nicht zurückschrecken, bei der Beschaffung von nicht allgemein zugänglichen Informationen und beim Einkauf von Gegenständen, die legal überhaupt nicht erhältlich sind, z.B. manche Zaubermittel oder Einbruchswerkzeug.\n
Wird Gassenwissen bei der Suche nach Informationen eingesetzt, steht einer angesprochenen Nichtspielerfigur ein Widerstandswurf (z.B. für Gassenwissen oder Menschenkenntnis oder In/10) zu, auch wenn der EW:Gassenwissen misslingt. Durchschaut ein ordentlicher Bürger die gesetzeswidrigen Absichten seines Gegenübers, der ihn z.B. in verschwörerischem Tonfall fragt, wo man denn hier „etwas organisieren“ könne, macht er eventuell Schwierigkeiten. Allerdings sind es die meisten normalen Menschen Midgards gewohnt, sich um ihre eigenen Angelegenheiten zu kümmern. Sie sind zu gleichgültig oder auch zu eingeschüchtert, um gleich zur Stadtwache zu rennen. Fragt ein Abenteurer nur nach unverfänglichen Dingen oder hört er sich unauffällig nach Gerüchten um, kann der Spielleiter auf den Widerstandswurf verzichten.\n
Gassenwissen lässt sich ähnlich wie Menschenkenntnis einsetzen, um diskret zu erkunden, ob jemand bestechlich ist.  Im Gegensatz zur Menschenkenntnis kann der Abenteurer mit Gassenwissen zusätzlich abschätzen, wie viel er bieten muss, um Aussicht auf Erfolg zu haben. Bei einem kritischen Erfolg erfährt er sogar, welche Mindestbestechungssumme ausreicht. Durchschaut der Gesprächspartner die Absicht des Abenteurers, liegt es ganz im Ermessen des Spielleiters, was die Person unternimmt. Ist sie einer Bestechung nicht abgeneigt, rückt sie vielleicht einfach mit der Sprache heraus und nennt ihren Preis. Ist sie unbestechlich, reagiert sie abweisend oder meldet den Versuch gar einem Vorgesetzten.\n
Gassenwissen beinhaltet auch das Wissen, wie man eine Person unauffällig im Trubel einer Stadt beschattet. Unauffällige Kleidung und Verhalten ermöglichen es, in der Menschenmenge unterzutauchen. Der Erfolgswurf muss jedes Mal neu gemacht werden, wenn der Verfolgte aus dem Sichtbereich des Beschatters verschwindet (weil er zum Beispiel durch eine vorüberfahrende Kutsche verdeckt wird oder der Verfolgte um eine Ecke geht oder ein Haus mit mehreren Ausgängen betritt). Solange die Erfolgswürfe gelingen, darf ein Beschatteter nur dann Widerstandswürfe ausführen, wenn er weiß, dass ihm jemand folgt. Misslingt jedoch ein Erfolgswurf, steht dem Beschatteten ähnlich wie bei anderen Fertigkeiten des sozialen Umgangs ein Widerstandswurf gegen Gassenwissen oder Wahrnehmung zu. Bei dessen Gelingen bemerkt er den Verfolger, durchschaut dessen Absichten und kann sich entsprechend verhalten. So kann er den Verfolger auf eine falsche Fährte locken oder ihm in einer günstigen Situation auch automatisch entkommen.", gruppe:"G", ungelernt: "+0", kategorie: "Halbwelt, Sozial, Unterwelt", text: "Gassenwissen" },
        { type:"Fertigkeiten", beschreibung:"Der Abenteurer kann jonglieren, Feuer oder Schwerter schlucken und ähnliche, auf seiner Geschicklichkeit beruhende Gauklerkunststücke vollbringen und damit sein Publikum unterhalten. Ein EW:Gaukeln ist nur nötig, wenn er mit seiner Vorführung etwas erreichen will, z.B. anschließend Geld sammeln oder die Aufmerksamkeit der Zuschauer auf sich lenken. Misslingt der Erfolgswurf, zeigt sich das Publikum unbeeindruckt.\n
Will der Gaukler seine Zuschauer ganz in seinen Bann ziehen, um sie von seinen Gefährten abzulenken oder selbst einem der Umstehenden, den er in seine Vorführung einbezieht, etwas zu stehlen, wird das als Einsatz einer Fertigkeit im sozialen Umgang behandelt. Dem Opfer -bei mehreren Personen derjenigen mit den besten Chancen -steht ein Widerstandswurf zu (meist für Menschenkenntnis, Gassenwissen oder In/10), ob es die Absicht des Gauklers durchschaut. Ein Gaukler kann gezielt improvisierte Wurfwaffen (s. S. 92) wie Münzen, Bälle, Steine, Bierkrüge und anderes werfen und dafür seinen Fertigkeitswert für Gaukeln einsetzen. Gelingt der EW:Gaukeln, wurde das Ziel (z.B. das anvisierte Feld von 1m×1m Größe) genau getroffen. Personen, Tieren und anderen Wesen steht ein WW:Abwehr zu. Gaukeln kann aber auch außerhalb des Kampfes benutzt werden, um zum Beispiel einem Freund etwas gezielt über eine größere Entfernung zuzuwerfen oder um eine brennende Fackel in eine Öllache zu werfen.\n
Mit Gaukeln kann ein Abenteurer auch reaktionsschnell Gegenstände fangen, die in höchstens 1 m Abstand vorbeifliegen. Ein Erfolgswurf ist nur unter erschwerten Bedingungen nötig: der Gegenstand ist sehr klein oder bewegt sich schnell, der Wurf kommt unerwartet, oder der Abstand zwischen Werfer und Fänger ist groß.", gruppe:"G", ungelernt: "+0", kategorie: "Halbwelt", text: "Gaukeln" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"G", ungelernt: "-", kategorie: "Kampf, Körperbeherrschung", text: "Geländelauf" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"G", ungelernt: "-", kategorie: "Alltag", text: "Gerätekunde" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"G", ungelernt: "-", kategorie: "Alltag", text: "Geschäftssinn" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"G", ungelernt: "-", kategorie: "Alltag, Halbwelt", text: "Glücksspiel" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"K", ungelernt: "-", kategorie: "Kampf", text: "Kampf in Vollrüstung" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"K", ungelernt: "-", kategorie: "Alltag, Halbwelt, Körperbeherrschung", text: "Klettern" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"L", ungelernt: "-", kategorie: "Körperbeherrschung", text: "Laufen" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"M", ungelernt: "-", kategorie: "Körperbeherrschung", text: "Meditieren" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"M", ungelernt: "-", kategorie: "Sozial", text: "Menschenkenntnis" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"M", ungelernt: "-", kategorie: "Unterwelt", text: "Meucheln" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"M", ungelernt: "-", kategorie: "Alltag", text: "Musizieren" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"N", ungelernt: "-", kategorie: "Freiland", text: "Naturkunde" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"P", ungelernt: "-", kategorie: "Freiland", text: "Pflanzenkunde" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"R", ungelernt: "-", kategorie: "Alltag, Kampf", text: "Reiten" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"R", ungelernt: "-", kategorie: "Kampf", text: "Reiterkampf" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"S", ungelernt: "-", kategorie: "Freiland, Unterwelt", text: "Schleichen" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"S", ungelernt: "-", kategorie: "Unterwelt", text: "Schlösser öffnen" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"S", ungelernt: "-", kategorie: "Alltag", text: "Schreiben" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"S", ungelernt: "-", kategorie: "Alltag, Körperbeherrschung", text: "Schwimmen" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"S", ungelernt: "-", kategorie: "Alltag", text: "Seilkunst" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"S", ungelernt: "-", kategorie: "Alltag", text: "Sprache" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"S", ungelernt: "-", kategorie: "Freiland, Unterwelt", text: "Spurensuche" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"S", ungelernt: "-", kategorie: "Halbwelt, Unterwelt", text: "Stehlen" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"T", ungelernt: "-", kategorie: "Freiland, Unterwelt", text: "Tarnen" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"T", ungelernt: "-", kategorie: "Körperbeherrschung", text: "Tauchen" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"T", ungelernt: "-", kategorie: "Freiland", text: "Tierkunde" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"U", ungelernt: "-", kategorie: "Freiland", text: "Überleben" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"V", ungelernt: "-", kategorie: "Sozial", text: "Verhören" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"V", ungelernt: "-", kategorie: "Sozial", text: "Verführen" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"V", ungelernt: "-", kategorie: "Sozial", text: "Verstellen" },
        { type:"Fertigkeiten", beschreibung:"", gruppe:"W", ungelernt: "-", kategorie: "Alltag", text: "Wagenlenken" },
    ]



}
