import QtQuick 2.0
import Felgo 3.0

/*

// EXAMPLE USAGE:
// add the following piece of code inside your App { } to display the List Page

ZauberList {

}

*/

ListPage {

    // TODO add your model
    model: [
        { type: "Zauber", gruppe:"A", art: "Wortzauber der Stufe 2", agens:"Beherrschen: Feuer•Wasser", ap:"2 je Wesen", zd:"Augenblick", reichweite:"30 m", ziel:"Geist", bereich:"bis zu 10 Wesen", dauer:"10 min", ursprung:"druidisch", text: "Angst", beschreibung:"Der Zauberer erscheint durch diesen Spruch dominant und furchteinflößend. Er schüchtert das Opfer ein, dessen animalische Instinkte es zu besonderer Vorsicht und Zurückhaltung
 zwingen. Es läuft nicht weg, sondern verharrt unsicher auf der Stelle, bleibt aber inaktiv und greift von sich aus nicht an. Befindet sich der einschüchternde Zauberer mehr als 1 min lang nicht im Blickfeld des Opfers, endet die Wirkung vorzeitig. Wesen, die einen höheren Grad als 10 haben, lassen sich nicht so leicht beeindrucken und sind immun gegen den Zauber Angst.\n
Angst ist ein schwacher Zauber. Von der Magie eingeschüchterte Wesen schütteln die Wirkung des Zaubers sofort ab, wenn sie selbst angegriffen werden oder wenn mit ihnen eng verbundene Wesen in einen Kampf verwickelt werden. Bei Menschen sind dies Verwandte, Freunde oder vertraute Kameraden, bei Tieren der eigene Nachwuchs, die Mitglieder des Rudels oder der geliebte menschliche Herr. Angriffe gegen Zufallsbekanntschaften eines mit Angst Verzauberten brechen die Wirkung des Spruches dagegen nicht. Die magische Angst endet auch, wenn der Verzauberte genügend stark motiviert ist, um einzugreifen; ein Zwerg mit seinem ausgeprägten Sinn für Besitz überwindet den Zauber, wenn sich jemand vor seinen Augen an seinen Schätzen vergreifen will. Der Spielleiter muss sich in die Persönlichkeit des Opfers hineinversetzen und abschätzen, ob Handlungen seiner Gegner ihm einen genügend starken Anlass liefern, die Angst abzuschütteln.\n
Angst wirkt nur auf Geschöpfe, die über einen eigenen Willen verfügen. Wird der Spruch auf ein Wesen angewandt, das von einem fremden Zauberer magisch beherrscht wird, entscheidet ein Zauberduell, welcher Einfluss die Oberhand behält."},
        { type: "Zauber",gruppe: "A", art: "Wortzauber der Stufe 2", agens:"Beherrschen: Luft•Wasser", ap:"2", zd:"10 sec", reichweite:"30 m", ziel:"Geist", bereich:"1 Wesen", dauer:"2 h", ursprung:"dämonisch", text: "Anstacheln", beschreibung:"Der Spruch bringt Personen mit einer aggressiven Grundstimmung dazu, aktiv Streit zu suchen. Das Ziel ihres Ärgers kann ein zufälliges Opfer sein, kann sich aber auch aus der Situation ergeben. Ein um seinen Lohn betrogener Hafenarbeiter kann die Waren seines Auftraggebers vor dessen Augen ins Wasser werfen, ein über hohe Brotpreise verärgerter Bürger kann Mitstreiter um sich scharen und ein Lebensmittellager plündern oder einen Bäcker angreifen, und eine Stadtwache mit einer tiefen Abneigung gegen Zauberer kann unvermittelt eine harmlose alte Frau als Hexe beschimpfen und verprügeln. Betrunkene suchen mit dem nächstbesten Opfer Streit, das sie für schwach genug halten. Zauberer, die Anstacheln einsetzen, sollten sich vorher gut informieren, auf wen ihr Opfer wütend ist, damit es nicht auf falsche Ziele oder gar gegen den Zauberer selbst losgeht."},
        { type: "Zauber",gruppe: "A", art: "Wortzauber der Stufe 2", agens:"Beherrschen: Wasser•Wasser", ap:"2", zd:"10 sec", reichweite:"30 m", ziel:"Geist", bereich:"1 Wesen", dauer:"6 h", ursprung:"dämonisch", text: "Anziehen", beschreibung:"Der Zauberer erhöht seine Attraktivität für eine andere Person derart, dass diese ihn sympathisch findet und sich zu ihm hingezogen fühlt. Unter anderem erhält er +6 auf EW:Verführen. Dem Zauber Verfallene helfen dem Zauberer jedoch nicht, wenn sie sich dafür großer Mühen unterziehen oder in Gefahr begeben müssten. Männer, die der Anziehung einer Hexe erlegen sind, werden sie nur bedauern und das Holz nicht eigenhändig entzünden, wenn sie auf dem Scheiterhaufen landet, aber nichts zu ihrer Rettung unternehmen. Die magische Anziehung spielt sich nur auf der animalischen Ebene ab; das Opfer verliebt sich nicht in den Zauberer und zeigt ihm gegenüber auch keine besondere Opferbereitschaft.\n
Die Wirkung des Spruches endet nur dann nach 6 Stunden, wenn dem Opfer ein EW:Resistenz gelingt. Andernfalls erliegt es für weitere 6 Stunden der magischen Anziehung, darf dann einen neuen EW:Resistenz würfeln usw.\n
Der Zauber wird vorzeitig gebrochen, wenn der Zauberer offensichtlich das Opfer oder dessen Freunde ernsthaft schädigt. Er kann keine Freunde der ihm verfallenen Person angreifen, ihr größere Summen Geld stehlen oder ihr Haus anzünden. Wenn der Zauberer geschickt ist, kann er seine wahren Absichten aber als Teil eines neckischen Spiels tarnen und zum Beispiel sein Opfer fesseln und dann mit einem schnellen Handgriff knebeln."},
        { type: "Zauber",gruppe: "A", art: "Gestenzauber der Stufe 1", agens:"Formen: Magan•Metall", ap:"1", zd:"10 sec", reichweite:"15 m", ziel:"Umgebung", bereich:"1 Objekt", dauer:"30 min", ursprung:"druidisch", text: "Auffrischen", beschreibung:"Der Zauberer kann Nahrung und Getränke bis zu einer Menge von 2 kg oder 2 Liter auffrischen. Abgestandenes Wasser ist eine Zeit lang wieder quellfrisch, saure Milch schmeckt wie frisch gemolken, und ranzige Speisen sind genießbar. Derart Aufgefrischtes verdirbt bald wieder, wenn es nicht sofort verzehrt wird. Mit dem Zauber kann man eine Mahlzeit auch einerseits schmackhaft würzen, andererseits versalzen oder durch zu viel Schärfe für normale Gaumen ungenießbar machen."},
        { type: "Zauber",gruppe: "A", art: "Gestenzauber der Stufe 12", agens:"Zerstören: Magan•Metall", ap:"8", zd:"30 sec", reichweite:"30 m", ziel:"Umgebung", bereich:"1 m Umkreis", dauer:"2 min, k", ursprung:"dämonisch", text: "Auflösung", beschreibung:"Um den Zauberer entsteht eine 2 m durchmessende, rotierende Sphäre aus einem Netz grünlicher Lichtfäden voller chaotischer Energie. Sie bewegt sich mit B12 geradlinig in eine einmal festgelegte Richtung, solange ihr Erschaffer sich auf sie konzentriert. Am Ende der Wirkungsdauer vergeht die Kugel in einer grünen Implosion, die alle feste Materie in ihrem Innern zu Staub werden lässt. Befindet sich ein Wesen in diesem Augenblick im Innern der Sphäre, entscheidet ein WW:Abwehr, ob es rechtzeitig aus dem Wirkungsbereich heraus springen kann und dabei nur 1W6 AP verliert. Andernfalls wird es zusammen mit seiner Ausrüstung vernichtet. Die Kugel implodiert vorzeitig, wenn die Konzentration des Zauberers endet. Befindet er sich dabei selbst noch im Innern der Sphäre, muss ihm ein WW:Abwehr gelingen, um nicht aufgelöst zu werden. Soll verzauberte Materie wie z.B. magische Artefakte, ein versteinerter Mensch oder eine Eiswand aufgelöst werden, muss der Zauberer ein Zauberduell gewinnen."},
        { type: "Zauber",gruppe: "A", art: "Gestenzauber der Stufe 4", agens:"Verändern: Eis•Erde", ap:"2", zd:"10 sec", reichweite:"15 m", ziel:"Körper", bereich:"1 Wesen", dauer:"2 min", ursprung:"elementar", text: "Auskühlen", beschreibung:"Der Zauber entzieht dem Opfer langsam seine Körperwärme. Anfangs wehrt der Körper sich noch mit einem erhöhten Stoffwechselumsatz, was das Opfer 2 AP pro Runde kostet. Ist am Ende der Wirkungsdauer noch ein Rest an Ausdauer vorhanden, endet die magische Wirkung. Hat das Opfer aber 0 AP, setzt sich der Auskühlungsprozess fort, und es verliert sofort und dann noch 30 min lang alle zwei Minuten 1 LP, insgesamt also 16 LP. Lebt es danach noch, endet die Wirkung des Spruchs. Sinken die LP aber unter 0, bleibt nur noch ein tief gefrorener Leichnam übrig, der dank der in seinem Inneren gebundenen magischen Kälte auch nicht von alleine auftaut.\n
Es ist möglich, den AP- und LP-Verlusten mit Handauflegen, Heilen von Wunden, Krafttrünken usw. entgegenzuwirken. Bannen von Kälte und andere die Umgebung erwärmende Zauber helfen nicht, da dem Körper die Wärme auf magische Weise entzogen wird und er innerlich auskühlt. Es ist möglich, einen Toten mit Auskühlen einzufrieren, um ihn später mit Erheben der Toten wiederzubeleben; ein WW:Resistenz entfällt in diesem Fall. Vor der Wiederbelebung muss erst der magische Frost gebannt werden."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 5", agens:"Zerstören: Feuer•Eis", ap:"4", zd:"10 min", reichweite:"0 m", ziel:"Umgebung", bereich:"3 m Umkreis", dauer:"8 h", ursprung:"elementar", text: "Bannen von Kälte", beschreibung:"Der Zauberer markiert den Wirkungsbereich mit einem Holzkohlestrich auf dem Boden. Im Innern bleibt es warm genug (ca. 15 Grad Celsius), um Lebewesen vor dem Erfrieren zu schützen. Der Zauber halbiert (aufgerundet) auch den Schaden durch magische Kälte, z.B. durch Eisiger Nebel oder Frostball."},
        { type: "Zauber",gruppe: "B", art: "Wortzauber der Stufe 2", agens:"Zerstören: Eis•Feuer", ap:"1", zd:"Augenblick", reichweite:"0 m", ziel:"Umgebung", bereich:"9 m Umkreis", dauer:"10 min", ursprung:"göttlich", text: "Bannen von Licht", beschreibung:"Im Wirkungsbereich des Spruchs, in dessen Mittelpunkt sich der Zauberer befindet und der sich mit ihm bewegt, wird alles sichtbare Licht gelöscht, und es entsteht eine Zone undurchdringlicher Dunkelheit. Mit Infrarotsicht bzw. Sehen in Dunkelheit kann man innerhalb der unnatürlichen Finsternis sehen. Ist ein Bereich gleichzeitig von Bannen von Licht und Bannen von Dunkelheit betroffen, entscheidet ein Zauberduell, welcher Zauberspruch sich durchsetzt. Der Zauberer kann die von ihm geschaffene Dunkelheit jederzeit vorzeitig aufheben."},
        { type: "Zauber",gruppe: "B", art: "Wortzauber der Stufe 4", agens:"Zerstören: Metall•Magan", ap:"4", zd:"2 min", reichweite:"15 m", ziel:"Umgebung", bereich:"1 Wesen/Objekt", dauer:"0", ursprung:"dämonisch", text: "Bannen von Zauberwerk", beschreibung:"Die meisten Zauber wirken durch die schöpferische oder zerstörerische Kraft des Chaos, der der Zauberer durch Manipulation des Magan den Weg bereitet. Diese Manipulation kann rückgängig gemacht werden, wenn ein Zauberer sich der Hilfe der ordnenden Mächte versichern und so die magische Störung im natürlichen Weltgefüge beseitigen kann. Er kann mit Bannen von Zauberwerk fremde Magie aufheben - vorausgesetzt, er bleibt Sieger in einem Zauberduell (s. S. 21f) gegen den Schöpfer des Zaubers, den er ungeschehen machen will. Der Zauberer muss festlegen, welches Wesen oder welchen Gegenstand er von welchem erkennbaren magischen Effekt befreien will. Bannen von Zauberwerk auf gut Glück gegen eine Person, die vielleicht irgendwie verzaubert sein könnte, hat keine Wirkung. Das Zauberduell entfällt, wenn ein Zauber aufgehoben werden soll, den der Zauberer selbst vollbracht hat (s. S. 21).\n
Magische Artefakte beruhen meistens auf denselben Prinzipien wie normale Zauberei. Ihre Magie kann daher mit Bannen von Zauberwerk aufgehoben werden. Bei außergewöhnlichen magischen Artefakten und auch bei mächtigen Zaubersprüchen ab Stufe 10 kann der Spielleiter das Bannen mit Abzügen auf den EW:Zaubern erschweren oder mehrfaches erfolgreiches Bannen verlangen, bevor die arkanen Kräfte endgültig weichen.\n
Dweomer kann mit Bannen von Zauberwerk nicht aufgehoben werden, da er seine arkane Wirkung allein durch Kontrolle des Flusses an Lebenskraft erzielt. Entsprechend können auch die Zauberlieder der Barden und die vergessene Namensmagie nicht mit Bannen von Zauberwerk neutralisiert werden, da sie ebenfalls auf andere Art wirken als normale Sprüche."},
        { type: "Zauber",gruppe: "B", art: "Wortzauber der Stufe 5", agens:"Beherrschen: Feuer•Luft", ap:"3", zd:"10 sec", reichweite:"15 m", ziel:"Geist", bereich:"1 Wesen", dauer:"10 min", ursprung:"dämonisch", text: "Beeinflussen", beschreibung:"Beeinflussen wirkt auf Wesen von menschlicher Intelligenz, mit denen der Zauberer reden oder sich auf magische Weise verständigen kann. Unter dem Einfluss des Spruches sind sie eher bereit, auf seine Vorschläge einzugehen, wenn sie ihnen sinnvoll erscheinen und er sie gut begründen kann. Magisch beeinflusste Opfer sind leichtgläubiger und finden den Zauberer sympathischer als normal. Eine Person, deren WW:Resistenz gelingt, durchschaut die Absicht des Zauberers, ihre Entscheidung magisch zu beeinflussen. Sie ist dann noch weniger geneigt, auf ihn zu hören."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 2", agens:"Bewegen: Magan•Metall", ap:"2", zd:"1 min", reichweite:"Berührung", ziel:"Umgebung", bereich:"1 Objekt", dauer:"1 Monat", ursprung:"dämonisch", text: "Befestigen", beschreibung:"Ein Seil, ein Holzstab, ein eiserner Griff und andere unbelebte Gegenstände bis zu 25 kg Gewicht können mit diesem Zauber an Boden, Wand oder Decke, aber auch an einem anderen unbelebten Objekt befestigt werden. Die Berührungsfläche, auf die der Zauberer während des Rituals spuckt, muss wenigstens 1 cm2 groß sein. Die magische Verbindung kann mit normalen Mitteln nicht gelöst werden. Der Zauberer selbst kann die Wirkung vorzeitig mit einem Willensakt aufheben, wenn er dabei die befestigte Stelle berührt. Besonders starke Wesen können den magisch befestigten Gegenstand mit roher Gewalt abreißen, wenn ihnen zwei Kraftakte gelingen. Meist reicht aber schon der erste Kraftakt, um das Seil zu zerreißen, den Stab zu zerbrechen usw., so dass diese Möglichkeit nur für Gegenstände aus Metall oder Stein eine Rolle spielt. Der Zauber wirkt nur auf die Verbindungsstelle und erhöht nicht die Stabilität des Gegenstands. Auch ein magisch befestigtes Seil reißt, wenn es zu sehr belastet wird, und es kann kurz unterhalb der Verbindungsstelle abgeschnitten werden."},
        { type: "Zauber",gruppe: "B", art: "Wortzauber der Stufe 3", agens:"Beherrschen: Wasser•Wasser", ap:"1 je Grad", zd:"10 sec", reichweite:"30 m", ziel:"Geist", bereich:"1 Wesen", dauer:"0", ursprung:"dämonisch", text: "Besänftigen", beschreibung:"Der Spruch wirkt beruhigend auf die Anima aggressiver Menschen oder ähnlich intelligenter Wesen ein. Sie werden davon überzeugt, dass der Zauberer und seine Begleiter Freunde sind und nichts Böses beabsichtigen. Auf diese Weise verzauberte Personen greifen nicht an, solange sie nicht direkt bedroht werden. Besänftigen hilft gegen gewalttätige Menschen, die in blinder Wut angreifen wollen oder die sich wegen eines leicht aufzuklärenden Missverständnisses gegen den Zauberer oder seine Gefährten gewandt haben. Der Zauber hilft nicht gegen Gegner, die wohlüberlegt und nicht nur aus einer Gefühlsaufwallung heraus gegen die Abenteurer vorgehen. Ein betrunkener Raufbold, den der Zauberer versehentlich angerempelt hat, oder ein wütender Ehemann, der einen Abenteurer mit dem Liebhaber seiner Frau verwechselt, lassen sich besänftigen, nicht aber der Räuber, der es auf das Gold des Zauberers abgesehen hat, oder der gedungene Meuchelmörder, der ein Opfer gegen Bezahlung umbringen will. Eine Person, deren WW:Resistenz gelingt, durchschaut die Absicht des Zauberers, sie magisch zu beeinflussen. Sie wird dann eher noch wütender.\n
Mit Besänftigen ist es auch möglich, Berserker zu beruhigen und wieder zu normalen Kämpfern zu machen. Der Spruch kann außerdem die Wirkung von Magie wie Anstacheln, Heiliger Zorn, Bärenwut oder das Lied des Zorns aufheben, wenn der Zauberer im Zauberduell die Oberhand behält."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 6", agens:"Veränder: Magan•Erde", ap:"6", zd:"10 sec", reichweite:"15 m", ziel:"Körper", bereich:"1 Wesen", dauer:"1 min", ursprung:"dämonisch", text: "Beschleunigen", beschreibung:"Der Zauberer kann ein Wesen beschleunigen. Dessen Bewegungsweite verdoppelt sich, und es kann zweimal pro Runde angreifen, wobei der zweite Angriff am Ende der jeweiligen Runde erfolgt. Der Zauber beeinflusst nur die körperlichen Reflexe, nicht aber die Denkgeschwindigkeit. Der Beschleunigte kann daher nicht doppelt so schnell zaubern, und auch andere Handlungen, die bewusstes Nachdenken erfordern, laufen nicht schneller ab. Der Zauber kann nicht auf Abenteurer angewandt werden, die eine Metallrüstung tragen, da diese von der Magie nicht beeinflusst wird und ihre Trägheit schnellere Bewegungen verhindert. Ein bereits beschleunigtes Wesen kann nicht nochmals beschleunigt werden."},
        { type: "Zauber",gruppe: "B", art: "Gedankenzauber der Stufe 6", agens:"Beherrschen:Wasser•Wasser", ap:"3", zd:"Augenblick", reichweite:"Berührung", ziel:"Geist", bereich:"1 km Umkreis", dauer:"2 h", ursprung:"dämonisch", text: "Binden des Vertrauten", beschreibung:"Der Zauberer kann ein Wirbeltier mit einem Gewicht von höchstens 10 kg und einer Intelligenz von mindestens t31 an sich binden, z.B. eine Katze, einen Affen, einen Raben, eine Kröte, eine Schlange oder eine Eule. Als ersten Schritt muss er vier Wochen lang von Vollmond bis Vollmond ohne Unterbrechung in Gesellschaft des Tieres verbringen. In den Vollmondnächten zu Beginn und Ende dieser Zeitspanne sowie in der Neumondnacht dazwischen muss der Zauberer Binden des Vertrauten anwenden. Scheitert nur einer der drei EW:Zaubern, eignet sich dieses Tier nicht zum Vertrauten.\n
Nach dem erfolgreichen Abschluss des Zaubervorgangs ist das Tier zum Vertrauten oder Familiar geworden. Die Animae von Zauberer und Vertrautem sind nun durch einen Silberfaden (s. »Von den Bestandteilen des Lebens«, S. 30) miteinander verknüpft, so dass letzterer dieselbe Resistenz wie sein Meister erhält. Durch die entstandene Seelenverwandtschaft hängt das Tier an seinem Herrn, wird ihm nicht davonlaufen und ihn nach Kräften verteidigen, wenn er angegriffen wird. Ein Zauberer kann gleichzeitig nur einen Vertrauten haben; bei dessen Tod erleidet er einen Schock, verliert 3W6 AP und kann 1W6 Stunden lang nicht zaubern.\n
Wendet der Zauberer Binden des Vertrauten auf das bereits zum Familiar gewordene Tier an, so kann er mit dessen Augen sehen, solange es den Wirkungsbereich des Spruches nicht verlässt. Er kann sogar Personen oder Dinge verzaubern, die er durch die Augen des Vertrauten sieht, als ob er selbst anwesend wäre (s. »Einschränkungen beim Zaubern«, S. 17). Für Zauberer, die ihr Augenlicht verloren haben, ist das Binden eines Vertrauten eine der wenigen Möglichkeiten, ihre Kunst auch weiterhin auszuüben. Berührungszauber können dabei nur eingesetzt werden, wenn der Zauberer das Ziel persönlich berührt."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 3", agens:"Beherrschen: Luft•Eis", ap:"2", zd:"20 sec", reichweite:"0 m", ziel:"Geist", bereich:"3 m Umkreis", dauer:"2 min", ursprung:"göttlich", text: "Blaue Bannsphäre", beschreibung:"Um den Zauberer herum entsteht eine schwach blau leuchtende Sphäre von 3 m Radius, die sich Wänden und Decken anpasst und sich dann nicht mehr bewegt. Untote können nicht in den geschützten Bereich eindringen. Sie können jedoch mit Fernwaffen und Zauberei gegen Abenteurer im geschützten Bereich vorgehen. Die Blaue Bannsphäre dehnt sich bei Vollendung des Spruches vom Zauberer her aus, so dass vom  Zauber betroffene übernatürliche Wesen aus dem Wirkungsbereich hinaus gedrängt werden.\n
Die Blaue Bannsphäre schadet den betroffenen Wesen nicht, aber sie spüren eine Ausstrahlung der lebendigen Seele des Zauberers, die ihnen äußerst unangenehm ist. Untote von wenigstens Grad 4 überwinden ihr Unbehagen, wenn ihnen ein WW:Resistenz gelingt; sie können dann die schützende Sphäre nach Belieben durchschreiten. Die Bannsphäre bleibt jedoch bestehen und wirkt weiterhin gegen andere Kreaturen."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 7", agens:"Beherrschen:Luft•Eis", ap:"4", zd:"10 sec", reichweite:"50 m", ziel:"Geist", bereich:"1 Wesen/Objekt", dauer:"1W6×10 min", ursprung:"dämonisch", text: "Blauer Zwingkreis", beschreibung:"Der Zauberer verschleiert das Äußere eines Wesens oder eines Gegenstands, ohne die wesentlichen Formmerkmale zu ändern. Dabei können die Ausmaße um ein Viertel vergrößert oder verkleinert werden. Blendwerk hat bei Menschen eher die Wirkung einer gekonnten Verkleidung als einer umfassenden illusionären Verwandlung. Ein normaler Mensch oder Gegenstand erscheint unter dem Zauber von Blendwerk außerordentlich schön und begehrenswert. Eine alte Mähre wird zum stolzen Schlachtross. Der grimmige Assassine erscheint als sympathischer Händler von nebenan. Der Bauer wird zum Ritter und der irdene Topf mit Kieseln zur goldenen Schale voller Edelsteine. Der zerlumpte Zauberer tritt als prächtig gekleideter Edelmann auf.\n
Der Größe des Wesens oder Gegenstands, dessen Aussehen verändert werden soll, sind Grenzen gesetzt: Der Spruch kann höchstens auf einen Riesen oder einen kleinen Wagen angewandt werden. Eine über die verwandelten Stellen gestreute Mischung aus Opalstaub und Ambra (20 GS je Anwendung) kann die Wirkungsdauer des Zaubers um Stunden verlängern.Gegenstände aus Metall können mit Blendwerk nicht verzaubert werden, da die ihnen innewohnenden antimagischen Kräfte zu stark sind. Anderen
Objekten kann allerdings das Aussehen von Metallen verliehen werden. Mit Eisen verträgt sich Blendwerk besonders schlecht. Dieses Metall kann den Zauber durch bloße Berührung brechen (s. »Besonderes zu Illusionszaubern«, S. 79). Daher ist es praktisch unmöglich, ein Wesen oder einen Gegenstand mit Blendwerk zu verändern, das von Eisen berührt wird, z.B. eine mit Eisenbändern umwundene Kiste oder einen Krieger in einem stählernen Kettenhemd.\n
Die Illusion von Blendwerk wirkt automatisch. Ein WW:Resistenz wird wie bei den meisten Illusionszaubern erst gewürfelt, wenn jemand ausdrücklich Verdacht schöpft oder wenn er durch eine illusionäre Gefahr LP zu verlieren droht (s. S. 80). Ein WW:Resistenz entscheidet auch, ob eine direkte Berührung mit Eisen das Blendwerk aufhebt (alter Trick der Gastwirte).\n
Werden mitverzauberte Gegenstände (z.B. Kleidung) abgelegt oder gemeinsam verzauberte Objekte (z.B. ein Haufen Kiesel) voneinander getrennt, wirkt das Blendwerk nicht mehr auf sie. Die kritische Entfernung beträgt 12 Meter."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 6", agens:"Erschaffen: Luft•Feuer", ap:"2 je Blitz", zd:"10 sec", reichweite:"200 m", ziel:"Umgebung", bereich:"1-10 Strahlen", dauer:"0", ursprung:"dämonisch", text: "Blitze schleudern", beschreibung:"Aus den Fingern des Zauberers schießen unter lautem Donner grell leuchtende und heiße Blitze hervor. Für jeden Blitz wird ein eigener WW:Abwehr gewürfelt; der EW:Zaubern zählt für alle Blitze. Ein Opfer des Spruches verliert je Blitz 1 AP, wenn sein Widerstandswurf gelingt, andernfalls 2 LP und 2W6 AP. Der Zauberer entscheidet, wie viele der 1-10 Strahlen er gegen welche Gegner richtet; alle Zielpersonen müssen sich aber am Ende der Zauberdauer in seinem Blickfeld befinden. Im Extremfall kann er gegen zehn verschiedene Wesen je einen Blitz oder zehn Blitze gegen eine Person richten.\n
Rüstung schützt bei Blitze schleudern nicht vor LP-Verlusten, da die extreme Hitze selbst durch einen Metallharnisch dringt und Verbrennungen der Haut verursacht. Der Zauber fügt brennbarer lebloser Materie geringen (2 Punkte) Schaden zu. Eine Holztür wird durch den heißen Blitz nur an einer Stelle verkohlt. Zu einem Brand kommt es bei dieser Art von kurzzeitigem Kontakt im Normalfall nicht; eine Ausnahme bilden nur besonders leicht entzündliche Stoffe wie Zunder oder Zauberöl."},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen", beschreibung:""},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen", beschreibung:""},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen", beschreibung:""},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen", beschreibung:""},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen", beschreibung:""},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen", beschreibung:""},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen", beschreibung:""},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen", beschreibung:""},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen", beschreibung:""},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen", beschreibung:""},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen", beschreibung:""},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen", beschreibung:""},
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Baum" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenklinge" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Erkennen von Gift" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Erkennen von Krankheit" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Feenfluch" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Feuerbienen" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Grüne Hand" },
,       { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Austreibung des Bösen" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen von Dunkelheit" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen von Finsterwerk" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen von Gift" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen von Dunkelheit" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Blutmeisterschaft" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Das Lied der Feier" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Das Lied der Liebe" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Das Lied der Lockung" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Das Lied der Ruhe" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Das Lied der Tapferkeit" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Das Lied der Feier" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Das Lied der Feier" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Das Lied der Feier" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Das Lied der Feier" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Der einschläfernde Gesang" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Der frohlockende Gesan©çç©çg" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen von Gift" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Bannen von Dunkelheit" },
        { type: "Zauber",gruppe: "", art: "", agens:"", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Blutmeisterschaft" },

    ]

    section.property: "type"

}
