import QtQuick 2.0
import Felgo 3.0


ListPage {
    id:listPageZauber
    section.property: "type"
    // Use a predefined delegate but change some of its layout parameters
    delegate: SimpleRow {
      onSelected: {
        navStack.popAllExceptFirstAndPush(zauberDetailPage, {
                                       modelZauber:item
                                     })
      }
    }

    Component { id: zauberDetailPage;  ZauberDetail { } }

    SectionSelect {
      id: sectionSelect
      anchors.right: parent.right
      target: listPageZauber.listView
      sectionProperty: "gruppe"
    }

    model: [
        { type: "Zauber", gruppe:"A", art: "Wortzauber der Stufe 2", agens:"Beherrschen: Feuer•Wasser", ap:"2 je Wesen", zd:"Augenblick", reichweite:"30 m", ziel:"Geist", bereich:"bis zu 10 Wesen", dauer:"10 min", ursprung:"druidisch", text: "Angst", beschreibung:"Der Zauberer erscheint durch diesen Spruch dominant und furchteinflößend. Er schüchtert das Opfer ein, dessen animalische Instinkte es zu besonderer Vorsicht und Zurückhaltung
 zwingen. Es läuft nicht weg, sondern verharrt unsicher auf der Stelle, bleibt aber inaktiv und greift von sich aus nicht an. Befindet sich der einschüchternde Zauberer mehr als 1 min lang nicht im Blickfeld des Opfers, endet die Wirkung vorzeitig. Wesen, die einen höheren Grad als 10 haben, lassen sich nicht so leicht beeindrucken und sind immun gegen den Zauber Angst.\n
Angst ist ein schwacher Zauber. Von der Magie eingeschüchterte Wesen schütteln die Wirkung des Zaubers sofort ab, wenn sie selbst angegriffen werden oder wenn mit ihnen eng verbundene Wesen in einen Kampf verwickelt werden. Bei Menschen sind dies Verwandte, Freunde oder vertraute Kameraden, bei Tieren der eigene Nachwuchs, die Mitglieder des Rudels oder der geliebte menschliche Herr. Angriffe gegen Zufallsbekanntschaften eines mit Angst Verzauberten brechen die Wirkung des Spruches dagegen nicht. Die magische Angst endet auch, wenn der Verzauberte genügend stark motiviert ist, um einzugreifen; ein Zwerg mit seinem ausgeprägten Sinn für Besitz überwindet den Zauber, wenn sich jemand vor seinen Augen an seinen Schätzen vergreifen will. Der Spielleiter muss sich in die Persönlichkeit des Opfers hineinversetzen und abschätzen, ob Handlungen seiner Gegner ihm einen genügend starken Anlass liefern, die Angst abzuschütteln.\n
Angst wirkt nur auf Geschöpfe, die über einen eigenen Willen verfügen. Wird der Spruch auf ein Wesen angewandt, das von einem fremden Zauberer magisch beherrscht wird, entscheidet ein Zauberduell, welcher Einfluss die Oberhand behält."},
        { type: "Zauber", gruppe: "A", art: "Wortzauber der Stufe 2", agens:"Beherrschen: Luft•Wasser", ap:"2", zd:"10 sec", reichweite:"30 m", ziel:"Geist", bereich:"1 Wesen", dauer:"2 h", ursprung:"dämonisch", text: "Anstacheln", beschreibung:"Der Spruch bringt Personen mit einer aggressiven Grundstimmung dazu, aktiv Streit zu suchen. Das Ziel ihres Ärgers kann ein zufälliges Opfer sein, kann sich aber auch aus der Situation ergeben. Ein um seinen Lohn betrogener Hafenarbeiter kann die Waren seines Auftraggebers vor dessen Augen ins Wasser werfen, ein über hohe Brotpreise verärgerter Bürger kann Mitstreiter um sich scharen und ein Lebensmittellager plündern oder einen Bäcker angreifen, und eine Stadtwache mit einer tiefen Abneigung gegen Zauberer kann unvermittelt eine harmlose alte Frau als Hexe beschimpfen und verprügeln. Betrunkene suchen mit dem nächstbesten Opfer Streit, das sie für schwach genug halten. Zauberer, die Anstacheln einsetzen, sollten sich vorher gut informieren, auf wen ihr Opfer wütend ist, damit es nicht auf falsche Ziele oder gar gegen den Zauberer selbst losgeht."},
        { type: "Zauber",gruppe: "A", art: "Wortzauber der Stufe 2", agens:"Beherrschen: Wasser•Wasser", ap:"2", zd:"10 sec", reichweite:"30 m", ziel:"Geist", bereich:"1 Wesen", dauer:"6 h", ursprung:"dämonisch", text: "Anziehen", beschreibung:"Der Zauberer erhöht seine Attraktivität für eine andere Person derart, dass diese ihn sympathisch findet und sich zu ihm hingezogen fühlt. Unter anderem erhält er +6 auf EW:Verführen. Dem Zauber Verfallene helfen dem Zauberer jedoch nicht, wenn sie sich dafür großer Mühen unterziehen oder in Gefahr begeben müssten. Männer, die der Anziehung einer Hexe erlegen sind, werden sie nur bedauern und das Holz nicht eigenhändig entzünden, wenn sie auf dem Scheiterhaufen landet, aber nichts zu ihrer Rettung unternehmen. Die magische Anziehung spielt sich nur auf der animalischen Ebene ab; das Opfer verliebt sich nicht in den Zauberer und zeigt ihm gegenüber auch keine besondere Opferbereitschaft.\n
Die Wirkung des Spruches endet nur dann nach 6 Stunden, wenn dem Opfer ein EW:Resistenz gelingt. Andernfalls erliegt es für weitere 6 Stunden der magischen Anziehung, darf dann einen neuen EW:Resistenz würfeln usw.\n
Der Zauber wird vorzeitig gebrochen, wenn der Zauberer offensichtlich das Opfer oder dessen Freunde ernsthaft schädigt. Er kann keine Freunde der ihm verfallenen Person angreifen, ihr größere Summen Geld stehlen oder ihr Haus anzünden. Wenn der Zauberer geschickt ist, kann er seine wahren Absichten aber als Teil eines neckischen Spiels tarnen und zum Beispiel sein Opfer fesseln und dann mit einem schnellen Handgriff knebeln."},
        { type: "Zauber",gruppe: "A", art: "Gestenzauber der Stufe 1", agens:"Formen: Magan•Metall", ap:"1", zd:"10 sec", reichweite:"15 m", ziel:"Umgebung", bereich:"1 Objekt", dauer:"30 min", ursprung:"druidisch", text: "Auffrischen", beschreibung:"Der Zauberer kann Nahrung und Getränke bis zu einer Menge von 2 kg oder 2 Liter auffrischen. Abgestandenes Wasser ist eine Zeit lang wieder quellfrisch, saure Milch schmeckt wie frisch gemolken, und ranzige Speisen sind genießbar. Derart Aufgefrischtes verdirbt bald wieder, wenn es nicht sofort verzehrt wird. Mit dem Zauber kann man eine Mahlzeit auch einerseits schmackhaft würzen, andererseits versalzen oder durch zu viel Schärfe für normale Gaumen ungenießbar machen."},
        { type: "Zauber",gruppe: "A", art: "Gestenzauber der Stufe 12", agens:"Zerstören: Magan•Metall", ap:"8", zd:"30 sec", reichweite:"30 m", ziel:"Umgebung", bereich:"1 m Umkreis", dauer:"2 min, k", ursprung:"dämonisch", text: "Auflösung", beschreibung:"Um den Zauberer entsteht eine 2 m durchmessende, rotierende Sphäre aus einem Netz grünlicher Lichtfäden voller chaotischer Energie. Sie bewegt sich mit B12 geradlinig in eine einmal festgelegte Richtung, solange ihr Erschaffer sich auf sie konzentriert. Am Ende der Wirkungsdauer vergeht die Kugel in einer grünen Implosion, die alle feste Materie in ihrem Innern zu Staub werden lässt. Befindet sich ein Wesen in diesem Augenblick im Innern der Sphäre, entscheidet ein WW:Abwehr, ob es rechtzeitig aus dem Wirkungsbereich heraus springen kann und dabei nur 1W6 AP verliert. Andernfalls wird es zusammen mit seiner Ausrüstung vernichtet. Die Kugel implodiert vorzeitig, wenn die Konzentration des Zauberers endet. Befindet er sich dabei selbst noch im Innern der Sphäre, muss ihm ein WW:Abwehr gelingen, um nicht aufgelöst zu werden. Soll verzauberte Materie wie z.B. magische Artefakte, ein versteinerter Mensch oder eine Eiswand aufgelöst werden, muss der Zauberer ein Zauberduell gewinnen."},
        { type: "Zauber",gruppe: "A", art: "Gestenzauber der Stufe 4", agens:"Verändern: Eis•Erde", ap:"2", zd:"10 sec", reichweite:"15 m", ziel:"Körper", bereich:"1 Wesen", dauer:"2 min", ursprung:"elementar", text: "Auskühlen", beschreibung:"Der Zauber entzieht dem Opfer langsam seine Körperwärme. Anfangs wehrt der Körper sich noch mit einem erhöhten Stoffwechselumsatz, was das Opfer 2 AP pro Runde kostet. Ist am Ende der Wirkungsdauer noch ein Rest an Ausdauer vorhanden, endet die magische Wirkung. Hat das Opfer aber 0 AP, setzt sich der Auskühlungsprozess fort, und es verliert sofort und dann noch 30 min lang alle zwei Minuten 1 LP, insgesamt also 16 LP. Lebt es danach noch, endet die Wirkung des Spruchs. Sinken die LP aber unter 0, bleibt nur noch ein tief gefrorener Leichnam übrig, der dank der in seinem Inneren gebundenen magischen Kälte auch nicht von alleine auftaut.\n
Es ist möglich, den AP- und LP-Verlusten mit Handauflegen, Heilen von Wunden, Krafttrünken usw. entgegenzuwirken. Bannen von Kälte und andere die Umgebung erwärmende Zauber helfen nicht, da dem Körper die Wärme auf magische Weise entzogen wird und er innerlich auskühlt. Es ist möglich, einen Toten mit Auskühlen einzufrieren, um ihn später mit Erheben der Toten wiederzubeleben; ein WW:Resistenz entfällt in diesem Fall. Vor der Wiederbelebung muss erst der magische Frost gebannt werden."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 5", agens:"Zerstören: Feuer•Eis", ap:"4", zd:"10 min", reichweite:"0 m", ziel:"Umgebung", bereich:"3 m Umkreis", dauer:"8 h", ursprung:"elementar", text: "Bannen von Kälte", beschreibung:"Der Zauberer markiert den Wirkungsbereich mit einem Holzkohlestrich auf dem Boden. Im Innern bleibt es warm genug (ca. 15 Grad Celsius), um Lebewesen vor dem Erfrieren zu schützen. Der Zauber halbiert (aufgerundet) auch den Schaden durch magische Kälte, z.B. durch Eisiger Nebel oder Frostball."},
        { type: "Zauber",gruppe: "B", art: "Wortzauber der Stufe 2", agens:"Zerstören: Eis•Feuer", ap:"1", zd:"Augenblick", reichweite:"0 m", ziel:"Umgebung", bereich:"9 m Umkreis", dauer:"10 min", ursprung:"göttlich", text: "Bannen von Licht", beschreibung:"Im Wirkungsbereich des Spruchs, in dessen Mittelpunkt sich der Zauberer befindet und der sich mit ihm bewegt, wird alles sichtbare Licht gelöscht, und es entsteht eine Zone undurchdringlicher Dunkelheit. Mit Infrarotsicht bzw. Sehen in Dunkelheit kann man innerhalb der unnatürlichen Finsternis sehen. Ist ein Bereich gleichzeitig von Bannen von Licht und Bannen von Dunkelheit betroffen, entscheidet ein Zauberduell, welcher Zauberspruch sich durchsetzt. Der Zauberer kann die von ihm geschaffene Dunkelheit jederzeit vorzeitig aufheben."},
        { type: "Zauber",gruppe: "B", art: "Wortzauber der Stufe 4", agens:"Zerstören: Metall•Magan", ap:"4", zd:"2 min", reichweite:"15 m", ziel:"Umgebung", bereich:"1 Wesen/Objekt", dauer:"0", ursprung:"dämonisch", text: "Bannen von Zauberwerk", beschreibung:"Die meisten Zauber wirken durch die schöpferische oder zerstörerische Kraft des Chaos, der der Zauberer durch Manipulation des Magan den Weg bereitet. Diese Manipulation kann rückgängig gemacht werden, wenn ein Zauberer sich der Hilfe der ordnenden Mächte versichern und so die magische Störung im natürlichen Weltgefüge beseitigen kann. Er kann mit Bannen von Zauberwerk fremde Magie aufheben - vorausgesetzt, er bleibt Sieger in einem Zauberduell (s. S. 21f) gegen den Schöpfer des Zaubers, den er ungeschehen machen will. Der Zauberer muss festlegen, welches Wesen oder welchen Gegenstand er von welchem erkennbaren magischen Effekt befreien will. Bannen von Zauberwerk auf gut Glück gegen eine Person, die vielleicht irgendwie verzaubert sein könnte, hat keine Wirkung. Das Zauberduell entfällt, wenn ein Zauber aufgehoben werden soll, den der Zauberer selbst vollbracht hat (s. S. 21).\n
Magische Artefakte beruhen meistens auf denselben Prinzipien wie normale Zauberei. Ihre Magie kann daher mit Bannen von Zauberwerk aufgehoben werden. Bei außergewöhnlichen magischen Artefakten und auch bei mächtigen Zaubersprüchen ab Stufe 10 kann der Spielleiter das Bannen mit Abzügen auf den EW:Zaubern erschweren oder mehrfaches erfolgreiches Bannen verlangen, bevor die arkanen Kräfte endgültig weichen.\n
Dweomer kann mit Bannen von Zauberwerk nicht aufgehoben werden, da er seine arkane Wirkung allein durch Kontrolle des Flusses an Lebenskraft erzielt. Entsprechend können auch die Zauberlieder der Barden und die vergessene Namensmagie nicht mit Bannen von Zauberwerk neutralisiert werden, da sie ebenfalls auf andere Art wirken als normale Sprüche."},
        { type: "Zauber",gruppe: "B", art: "Wortzauber der Stufe 5", agens:"Beherrschen: Feuer•Luft", ap:"3", zd:"10 sec", reichweite:"15 m", ziel:"Geist", bereich:"1 Wesen", dauer:"10 min", ursprung:"dämonisch", text: "Beeinflussen", beschreibung:"Beeinflussen wirkt auf Wesen von menschlicher Intelligenz, mit denen der Zauberer reden oder sich auf magische Weise verständigen kann. Unter dem Einfluss des Spruches sind sie eher bereit, auf seine Vorschläge einzugehen, wenn sie ihnen sinnvoll erscheinen und er sie gut begründen kann. Magisch beeinflusste Opfer sind leichtgläubiger und finden den Zauberer sympathischer als normal. Eine Person, deren WW:Resistenz gelingt, durchschaut die Absicht des Zauberers, ihre Entscheidung magisch zu beeinflussen. Sie ist dann noch weniger geneigt, auf ihn zu hören."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 2", agens:"Bewegen: Magan•Metall", ap:"2", zd:"1 min", reichweite:"Berührung", ziel:"Umgebung", bereich:"1 Objekt", dauer:"1 Monat", ursprung:"dämonisch", text: "Befestigen", beschreibung:"Ein Seil, ein Holzstab, ein eiserner Griff und andere unbelebte Gegenstände bis zu 25 kg Gewicht können mit diesem Zauber an Boden, Wand oder Decke, aber auch an einem anderen unbelebten Objekt befestigt werden. Die Berührungsfläche, auf die der Zauberer während des Rituals spuckt, muss wenigstens 1 cm2 groß sein. Die magische Verbindung kann mit normalen Mitteln nicht gelöst werden. Der Zauberer selbst kann die Wirkung vorzeitig mit einem Willensakt aufheben, wenn er dabei die befestigte Stelle berührt. Besonders starke Wesen können den magisch befestigten Gegenstand mit roher Gewalt abreißen, wenn ihnen zwei Kraftakte gelingen. Meist reicht aber schon der erste Kraftakt, um das Seil zu zerreißen, den Stab zu zerbrechen usw., so dass diese Möglichkeit nur für Gegenstände aus Metall oder Stein eine Rolle spielt. Der Zauber wirkt nur auf die Verbindungsstelle und erhöht nicht die Stabilität des Gegenstands. Auch ein magisch befestigtes Seil reißt, wenn es zu sehr belastet wird, und es kann kurz unterhalb der Verbindungsstelle abgeschnitten werden."},
        { type: "Zauber",gruppe: "B", art: "Wortzauber der Stufe 3", agens:"Beherrschen: Wasser•Wasser", ap:"1 je Grad", zd:"10 sec", reichweite:"30 m", ziel:"Geist", bereich:"1 Wesen", dauer:"0", ursprung:"dämonisch", text: "Besänftigen", beschreibung:"Der Spruch wirkt beruhigend auf die Anima aggressiver Menschen oder ähnlich intelligenter Wesen ein. Sie werden davon überzeugt, dass der Zauberer und seine Begleiter Freunde sind und nichts Böses beabsichtigen. Auf diese Weise verzauberte Personen greifen nicht an, solange sie nicht direkt bedroht werden. Besänftigen hilft gegen gewalttätige Menschen, die in blinder Wut angreifen wollen oder die sich wegen eines leicht aufzuklärenden Missverständnisses gegen den Zauberer oder seine Gefährten gewandt haben. Der Zauber hilft nicht gegen Gegner, die wohlüberlegt und nicht nur aus einer Gefühlsaufwallung heraus gegen die Abenteurer vorgehen. Ein betrunkener Raufbold, den der Zauberer versehentlich angerempelt hat, oder ein wütender Ehemann, der einen Abenteurer mit dem Liebhaber seiner Frau verwechselt, lassen sich besänftigen, nicht aber der Räuber, der es auf das Gold des Zauberers abgesehen hat, oder der gedungene Meuchelmörder, der ein Opfer gegen Bezahlung umbringen will. Eine Person, deren WW:Resistenz gelingt, durchschaut die Absicht des Zauberers, sie magisch zu beeinflussen. Sie wird dann eher noch wütender.\n
Mit Besänftigen ist es auch möglich, Berserker zu beruhigen und wieder zu normalen Kämpfern zu machen. Der Spruch kann außerdem die Wirkung von Magie wie Anstacheln, Heiliger Zorn, Bärenwut oder das Lied des Zorns aufheben, wenn der Zauberer im Zauberduell die Oberhand behält."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 6", agens:"Veränder: Magan•Erde", ap:"6", zd:"10 sec", reichweite:"15 m", ziel:"Körper", bereich:"1 Wesen", dauer:"1 min", ursprung:"dämonisch", text: "Beschleunigen", beschreibung:"Der Zauberer kann ein Wesen beschleunigen. Dessen Bewegungsweite verdoppelt sich, und es kann zweimal pro Runde angreifen, wobei der zweite Angriff am Ende der jeweiligen Runde erfolgt. Der Zauber beeinflusst nur die körperlichen Reflexe, nicht aber die Denkgeschwindigkeit. Der Beschleunigte kann daher nicht doppelt so schnell zaubern, und auch andere Handlungen, die bewusstes Nachdenken erfordern, laufen nicht schneller ab. Der Zauber kann nicht auf Abenteurer angewandt werden, die eine Metallrüstung tragen, da diese von der Magie nicht beeinflusst wird und ihre Trägheit schnellere Bewegungen verhindert. Ein bereits beschleunigtes Wesen kann nicht nochmals beschleunigt werden."},
        { type: "Zauber",gruppe: "B", art: "Gedankenzauber der Stufe 6", agens:"Beherrschen:Wasser•Wasser", ap:"3", zd:"Augenblick", reichweite:"Berührung", ziel:"Geist", bereich:"1 km Umkreis", dauer:"2 h", ursprung:"dämonisch", text: "Binden des Vertrauten", beschreibung:"Der Zauberer kann ein Wirbeltier mit einem Gewicht von höchstens 10 kg und einer Intelligenz von mindestens t31 an sich binden, z.B. eine Katze, einen Affen, einen Raben, eine Kröte, eine Schlange oder eine Eule. Als ersten Schritt muss er vier Wochen lang von Vollmond bis Vollmond ohne Unterbrechung in Gesellschaft des Tieres verbringen. In den Vollmondnächten zu Beginn und Ende dieser Zeitspanne sowie in der Neumondnacht dazwischen muss der Zauberer Binden des Vertrauten anwenden. Scheitert nur einer der drei EW:Zaubern, eignet sich dieses Tier nicht zum Vertrauten.\n
Nach dem erfolgreichen Abschluss des Zaubervorgangs ist das Tier zum Vertrauten oder Familiar geworden. Die Animae von Zauberer und Vertrautem sind nun durch einen Silberfaden (s. »Von den Bestandteilen des Lebens«, S. 30) miteinander verknüpft, so dass letzterer dieselbe Resistenz wie sein Meister erhält. Durch die entstandene Seelenverwandtschaft hängt das Tier an seinem Herrn, wird ihm nicht davonlaufen und ihn nach Kräften verteidigen, wenn er angegriffen wird. Ein Zauberer kann gleichzeitig nur einen Vertrauten haben; bei dessen Tod erleidet er einen Schock, verliert 3W6 AP und kann 1W6 Stunden lang nicht zaubern.\n
Wendet der Zauberer Binden des Vertrauten auf das bereits zum Familiar gewordene Tier an, so kann er mit dessen Augen sehen, solange es den Wirkungsbereich des Spruches nicht verlässt. Er kann sogar Personen oder Dinge verzaubern, die er durch die Augen des Vertrauten sieht, als ob er selbst anwesend wäre (s. »Einschränkungen beim Zaubern«, S. 17). Für Zauberer, die ihr Augenlicht verloren haben, ist das Binden eines Vertrauten eine der wenigen Möglichkeiten, ihre Kunst auch weiterhin auszuüben. Berührungszauber können dabei nur eingesetzt werden, wenn der Zauberer das Ziel persönlich berührt."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 3", agens:"Beherrschen: Luft•Eis", ap:"2", zd:"20 sec", reichweite:"0 m", ziel:"Geist", bereich:"3 m Umkreis", dauer:"2 min", ursprung:"göttlich", text: "Blaue Bannsphäre", beschreibung:"Um den Zauberer herum entsteht eine schwach blau leuchtende Sphäre von 3 m Radius, die sich Wänden und Decken anpasst und sich dann nicht mehr bewegt. Untote können nicht in den geschützten Bereich eindringen. Sie können jedoch mit Fernwaffen und Zauberei gegen Abenteurer im geschützten Bereich vorgehen. Die Blaue Bannsphäre dehnt sich bei Vollendung des Spruches vom Zauberer her aus, so dass vom  Zauber betroffene übernatürliche Wesen aus dem Wirkungsbereich hinaus gedrängt werden.\n
Die Blaue Bannsphäre schadet den betroffenen Wesen nicht, aber sie spüren eine Ausstrahlung der lebendigen Seele des Zauberers, die ihnen äußerst unangenehm ist. Untote von wenigstens Grad 4 überwinden ihr Unbehagen, wenn ihnen ein WW:Resistenz gelingt; sie können dann die schützende Sphäre nach Belieben durchschreiten. Die Bannsphäre bleibt jedoch bestehen und wirkt weiterhin gegen andere Kreaturen."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 7", agens:"Beherrschen:Luft•Eis", ap:"4", zd:"10 sec", reichweite:"50 m", ziel:"Geist", bereich:"1 Wesen/Objekt", dauer:"1W6×10 min", ursprung:"dämonisch", text: "Blauer Zwingkreis", beschreibung:"Der Zauberer verschleiert das Äußere eines Wesens oder eines Gegenstands, ohne die wesentlichen Formmerkmale zu ändern. Dabei können die Ausmaße um ein Viertel vergrößert oder verkleinert werden. Blendwerk hat bei Menschen eher die Wirkung einer gekonnten Verkleidung als einer umfassenden illusionären Verwandlung. Ein normaler Mensch oder Gegenstand erscheint unter dem Zauber von Blendwerk außerordentlich schön und begehrenswert. Eine alte Mähre wird zum stolzen Schlachtross. Der grimmige Assassine erscheint als sympathischer Händler von nebenan. Der Bauer wird zum Ritter und der irdene Topf mit Kieseln zur goldenen Schale voller Edelsteine. Der zerlumpte Zauberer tritt als prächtig gekleideter Edelmann auf.\n
Der Größe des Wesens oder Gegenstands, dessen Aussehen verändert werden soll, sind Grenzen gesetzt: Der Spruch kann höchstens auf einen Riesen oder einen kleinen Wagen angewandt werden. Eine über die verwandelten Stellen gestreute Mischung aus Opalstaub und Ambra (20 GS je Anwendung) kann die Wirkungsdauer des Zaubers um Stunden verlängern.Gegenstände aus Metall können mit Blendwerk nicht verzaubert werden, da die ihnen innewohnenden antimagischen Kräfte zu stark sind. Anderen
Objekten kann allerdings das Aussehen von Metallen verliehen werden. Mit Eisen verträgt sich Blendwerk besonders schlecht. Dieses Metall kann den Zauber durch bloße Berührung brechen (s. »Besonderes zu Illusionszaubern«, S. 79). Daher ist es praktisch unmöglich, ein Wesen oder einen Gegenstand mit Blendwerk zu verändern, das von Eisen berührt wird, z.B. eine mit Eisenbändern umwundene Kiste oder einen Krieger in einem stählernen Kettenhemd.\n
Die Illusion von Blendwerk wirkt automatisch. Ein WW:Resistenz wird wie bei den meisten Illusionszaubern erst gewürfelt, wenn jemand ausdrücklich Verdacht schöpft oder wenn er durch eine illusionäre Gefahr LP zu verlieren droht (s. S. 80). Ein WW:Resistenz entscheidet auch, ob eine direkte Berührung mit Eisen das Blendwerk aufhebt (alter Trick der Gastwirte).\n
Werden mitverzauberte Gegenstände (z.B. Kleidung) abgelegt oder gemeinsam verzauberte Objekte (z.B. ein Haufen Kiesel) voneinander getrennt, wirkt das Blendwerk nicht mehr auf sie. Die kritische Entfernung beträgt 12 Meter."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 6", agens:"Erschaffen: Luft•Feuer", ap:"2 je Blitz", zd:"10 sec", reichweite:"200 m", ziel:"Umgebung", bereich:"1-10 Strahlen", dauer:"0", ursprung:"dämonisch", text: "Blitze schleudern", beschreibung:"Aus den Fingern des Zauberers schießen unter lautem Donner grell leuchtende und heiße Blitze hervor. Für jeden Blitz wird ein eigener WW:Abwehr gewürfelt; der EW:Zaubern zählt für alle Blitze. Ein Opfer des Spruches verliert je Blitz 1 AP, wenn sein Widerstandswurf gelingt, andernfalls 2 LP und 2W6 AP. Der Zauberer entscheidet, wie viele der 1-10 Strahlen er gegen welche Gegner richtet; alle Zielpersonen müssen sich aber am Ende der Zauberdauer in seinem Blickfeld befinden. Im Extremfall kann er gegen zehn verschiedene Wesen je einen Blitz oder zehn Blitze gegen eine Person richten.\n
Rüstung schützt bei Blitze schleudern nicht vor LP-Verlusten, da die extreme Hitze selbst durch einen Metallharnisch dringt und Verbrennungen der Haut verursacht. Der Zauber fügt brennbarer lebloser Materie geringen (2 Punkte) Schaden zu. Eine Holztür wird durch den heißen Blitz nur an einer Stelle verkohlt. Zu einem Brand kommt es bei dieser Art von kurzzeitigem Kontakt im Normalfall nicht; eine Ausnahme bilden nur besonders leicht entzündliche Stoffe wie Zunder oder Zauberöl."},
        { type: "Zauber",gruppe: "B", art: "Gedankenzauber der Stufe 4", agens:"Zerstören: Eis•Holz", ap:"2", zd:"10 sec", reichweite:"15 m", ziel:"Körper", bereich:"1 Wesen", dauer:"unendlich", ursprung:"schwarzmagisch", text: "Böser Blick", beschreibung:"Der intensive Blick des Zauberers verursacht einen kurzen Schwindelanfall beim Opfer, das sofort 1W6–1 AP verliert. Gleichzeitig beginnt sein Fleisch, innerlich zu verrotten. Das Opfer verliert am Ende eines jeden Tages, an dem es unter diesem mächtigen Fluch leidet, 2 LP. Die so verlorenen Lebenspunkte können nur auf magischem Weg (z.B. Heilen von Wunden, Heilen schwerer Wunden, Allheilung, Zauberwerk mit vergleichbarer Wirkung) wieder zurückgewonnen werden. Heilen von Krankheit hält den Verwesungsvorgang für 24 Stunden auf; danach verliert das Opfer erneut Lebenspunkte. Mit dem Bösen Blick kann ein Zauberer auch pflanzliches Material langsam verrotten lassen und so Ernten verderben. Die einmalige Anwendung des Spruches reicht für etwa 1 m3 lebende Pflanzen, also zum Beispiel für einen ca. 5 m hohen und 50 cm durchmessenden Baum oder für ein 100 m2 großes Feld mit jungen Korn- oder Gemüsepflanzen.\n
Endgültig kann der Zauber nur auf drei Arten gebrochen werden:
- durch Anwenden der drei Zauber Bannen von Finsterwerk, Bannen von Zauberwerk und Heilen von Krankheit auf den Verzauberten innerhalb einer halben Stunde,
- durch den Tod des Zauberers, der den Bösen Blick angewandt hat,
- indem der Zauberer seinen Fluch in Anwesenheit des Opfers zurücknimmt.\n
Die Bevölkerung fürchtet diesen Zauber so sehr, dass manchmal bereits der Verdacht genügt, ein Zauberer habe den Bösen Blick, damit sich ein Volkshaufen zusammenrottet und den Verdächtigen steinigt oder verbrennt."},
        { type: "Zauber",gruppe: "B", art: "Gestenzauber der Stufe 1", agens:"Erschaffen:Holz•Wasser", ap:"3", zd:"10 min", reichweite:"0 m ", ziel:"Umgebung", bereich:"-", dauer:"0", ursprung:"dämonisch", text: "Brot und Wasser", beschreibung:"Der Zauberer erschafft 1 Pfund Brot und 2 Liter Wasser. Zum Auffangen des Wassers braucht der Zauberer ein Gefäß, z.B. einen Krug oder einen Wasserschlauch."},
        { type: "Zauber",gruppe: "D", art: "Gestenzauber der Stufe 5", agens:"Erschaffen: Magan•Magan", ap:"3", zd:"10 sec", reichweite:"30 m", ziel:"Umgebung", bereich:"Strahl", dauer:"2 min, k", ursprung:"dämonisch", text: "Dämonenfeuer", beschreibung:"Der Spruch erzeugt einmal pro Runde ein pfeilförmiges Geschoss aus geisterhaften, fahlgrünen Flammen, das der Zauberer gegen einen Gegner richten kann. Er kann dabei immer denselben oder in jeder Runde einen anderen Gegner anvisieren. Die Angriffe erfolgen mit Fertigkeitswert +8 und richten 1W6 Schaden an, wobei Rüstung LP-Verluste verringert. Bei Treffern vergehen die Lichtpfeile in einer Explosion, die auch Gegenstände wie zum Beispiel Türen beschädigen können. Das magische Feuer ist allerdings zu kalt, um brennbares Material zu entzünden. Während er sein Dämonenfeuer einsetzt, muss sich der Zauberer konzentrieren."},
        { type: "Zauber",gruppe: "D", art: "Gestenzauber der Stufe 6", agens:"Erschaffen: Magan•Magan", ap:"4", zd:"10 sec", reichweite:"50 m", ziel:"Umgebung", bereich:"Strahl", dauer:"2 min, k", ursprung:"dämonisch", text: "Dämonenkugeln", beschreibung:"Diese verbesserte Version des Spruchs Dämonenfeuer erzeugt etwa 30 cm große kugelförmige Geschosse aus fahlgrünem Feuer, die wegen ihrer Größe eine höhere Trefferchance haben. Die Angriffe erfolgen mit Fertigkeitswert +10 und richten 1W6 Schaden an. Im Übrigen gelten dieselben Regeln wie für Dämonenfeuer."},
        { type: "Zauber",gruppe: "D", art: "Gestenzauber der Stufe 6", agens:"Erschaffen: Magan • Magan", ap:"4", zd:"10 sec", reichweite:"0 m ", ziel:"Umgebung", bereich:"-", dauer:"2 min", ursprung:"dämonisch", text: "Dämonenschwert", beschreibung:"Der Spruch lässt aus der geballten Faust des Zauberers eine etwa 1,50 m lange Flammenklinge entspringen, die aus demselben fahlgrünen Feuer wie die Dämonenfeuerpfeile besteht.\n
Das Lichtschwert flackert in der Hand des Zauberers und ruft bei der leisesten Berührung grellgrüne Lichtblitze hervor. Er kann mit dieser immateriellen Waffe im Nahkampf mit dem Fertigkeitswert +8 angreifen und 2W6 Schaden anrichten. Rüstung nützt gegen diese Art von magischer Klinge, und das Dämonenschwert kann auch Gegenständen 2W6 Schaden zufügen. Da die Waffe kein Gewicht hat, kann der Zauberer bis zu 3 nebeneinander stehende Gegner gleichzeitig treffen - wie bei einem Rundumschlag, aber ohne die damit verbundenen Nachteile."},
        { type: "Zauber",gruppe: "D", art: "Wortzauber der Stufe 3", agens:"Verändern: Magan • Wasser", ap:"1", zd:"10 min", reichweite:"-", ziel:"Körper", bereich:"Zauberer", dauer:"10 min", ursprung:"dämonisch", text: "Dämonische Zaubermacht", beschreibung:"Dieser Zauber steigert das Talent des Zauberers, die Mächte des Chaos zu nutzen und Magie zu wirken. Er erhält einen Zuschlag von +2 auf alle EW:Zaubern für Sprüche, die vor Ablauf der Wirkungsdauer begonnen werden."},
        { type: "Zauber",gruppe: "D", art: "Gestenzauber der Stufe 7", agens:"Zerstören: Magan•Magan", ap:"6", zd:"10 sec", reichweite:"0 m", ziel:"Umgebung", bereich:"6 m Umkreis", dauer:"8 h, ", ursprung:"dämonisch", text: "Deckmantel", beschreibung:"Der Deckmantel bewegt sich mit dem Zauberer, der sich stets im Zentrum des Wirkungsbereiches befindet. Er schützt gegen alle Versuche, auf magischem Wege Informationen über Personen oder Gegenstände zu erhalten. Mit Zauberauge, Sehen von Verborgenem oder einer Kristallkugel sieht man wabernde Nebel, mit Lauschen hört man bloß ein undefinierbares Rauschen, Erkennen der Aura und Erkennen von Zauberei entdecken nichts Übernatürliches, Visionen sind verwirrend usw. Wird ein solcher Zauber gegen den Wirkungsbereich des Deckmantels eingesetzt, entscheidet ein Zauberduell, ob der Schutz wirkt. Verliert der Zauberer, der den Schutzzauber gewoben hat, das Duell, bricht sein Deckmantel zusammen. Gewinnt er das Duell, bemerkt er den magischen Spionageversuch. Um den schützenden Zauber aufrechtzuerhalten, muss der Zauberer sich während der Wirkungsdauer konzentrieren.
"},
        { type: "Zauber",gruppe: "D", art: "Gedankenzauber der Stufe 1", agens:"Zerstören: Magan • Magan", ap:"1", zd:"10 min", reichweite:"Berührung", ziel:"Geist", bereich:"1 Objekt", dauer:"12 h", ursprung:"dämonisch", text: "Dinge verbergen", beschreibung:"Der Zauber schützt einen magischen Gegenstand vor den Sprüchen Dinge wiederfinden, Erkennen von Zauberei und vor anderen magischen Versuchen, etwas über seinen Aufenthaltsort oder seine Eigenschaften herauszufinden. Wie bei Deckmantel entscheidet ein Zauberduell, ob der Schutz stark genug ist."},
        { type: "Zauber",gruppe: "D", art: "Gedankenzauber der Stufe 1", agens:"Erkennen: Magan • Metall", ap:"1", zd:"10 min", reichweite:"unbegrenzt", ziel:"Geist", bereich:"1 Objekt", dauer:"10 min", ursprung:"dämonisch", text: "Dinge wiederfinden", beschreibung:"Der Benutzer spürt während der ganzen Wirkungsdauer, wo sich ein magischer Gegenstand befindet, den er längere Zeit besessen und benutzt hat. Die Reichweite des Spruches ist unbegrenzt. Der Zauberer kann die Richtung, in der das gesuchte Objekt zu finden ist, nur bis auf 20 Grad genau bestimmen, und spürt auch die Entfernung zu seinem Eigentum nur ungefähr (bis 10 m, 10-100 m, 100 m-1 km, 1-10 km usw.). Der Spruch ist wirkungslos, wenn der gesuchte Gegenstand zerstört, in seine Bestandteile zerlegt worden ist oder sich in einer anderen Welt des Multiversums befindet."},
        { type: "Zauber",gruppe: "D", art: "Gestenzauber der Stufe 8", agens:"Erschaffen: Luft • Feuer", ap:"4", zd:"10 sec", reichweite:"50 m", ziel:"Umgebung", bereich:"Strahl", dauer:"0", ursprung:"dämonisch", text: "Donnerkeil", beschreibung:"Gegen Ende des Rituals schließt der Zauberer seine Hände um die Hornmurmel und öffnet sie dann langsam wieder. Aus der Murmel schießt ein heller Kugelblitz hervor und fliegt schnurstracks auf das Ziel zu. Sobald er dort einschlägt, ertönt ein weithin hörbarer Donner. Ein Opfer des Spruches verliert 1W6 AP, wenn sein WW:Abwehr gelingt. Andernfalls erleidet es 2W6+1 schweren Schaden, gegen den wie Blitze schleudern Rüstung nicht hilft. Der Donnerkeil fügt brennbarer lebloser Materie ebenfalls 2W6+1 Schaden zu. Zu einem Brand kommt es durch den kurzen Kontakt im Normalfall nicht. Nur leicht entzündliche Stoffe wie Zunder, trockenes Laub und Pergament oder Zauberöl gehen in Flammen auf."},
        { type: "Zauber",gruppe: "D", art: "Gestenzauber der Stufe 1", agens:"Erkennen: Magan • Feuer", ap:"1", zd:"10 sec", reichweite:"0 m", ziel:"Umgebung", bereich:"100 m Umkreis", dauer:"10 min", ursprung:"elementar", text: " Drittes Auge", beschreibung:"Für die Dauer des Zaubers schwebt der augenförmige, pflaumengroße Kristall zwei Handspannen vor der Stirn des Zauberers. Er ist normalerweise durchsichtig, leuchtet aber orangerot auf, wenn sich in bis zu 100 m Entfernung Wesen aus anderen Ebenen, also Dämonen oder Elementarwesen befinden. An der Intensität der Strahlung kann man ungefähr erkennen, wie gefährlich das stärkste der entdeckten Wesen im Vergleich zu bekannten Kreaturen ist. Weitere Informationen erhält der Zauberer nicht. Wesen ab Grad 4, die vom Dritten Auge entdeckt werden, dürfen einen EW:Resistenz gegen Geisteszauber würfeln. Haben sie dabei Erfolg, spüren sie ihrerseits die Ausstrahlung des Dritten Auges und sind vor der Anwesenheit eines Zauberers gewarnt"},
        { type: "Zauber",gruppe: "D", art: "Gestenzauber der Stufe 4", agens:"Erschaffen: Holz • Holz", ap:"1 je m Breite", zd:"10 sec", reichweite:"15m", ziel:"Umgebung", bereich:"-", dauer:"10 min", ursprung:"elementar", text: "Dschungelwand", beschreibung:"Der Zauberer erschafft eine 1 m dicke, unbewegliche magische Wand aus mit Schlingpflanzen überwuchertem Gestrüpp voller Blätter und giftiger Dornen. Sie entsteht in bis zu 15 m Entfernung, reicht vom Boden bis zur Decke eines Raumes, maximal aber bis in eine Höhe von 6 m, und ist undurchsichtig. Die Pflanzen wachsen langsam genug aus dem Boden empor, dass Wesen sich ohne Mühe rechtzeitig aus dem betroffenen Bereich entfernen können. Der Zauberer kann die Dschungelwand auch vor Ende der Wirkungsdauer verschwinden lassen, wenn er dies will.\n
Das gewaltsame Durchbrechen der Dschungelwand zählt als Kraftakt. Ein Abenteurer verliert dabei durch Dornenkratzer 1W6+2 Lebens- und Ausdauerpunkte, wogegen Rüstung schützt. Verliert er LP, muss er zusätzlich 2 Prüfwürfe gegen Gift machen. Misslingt der erste Wurf, stirbt der vergiftete Abenteurer innerhalb von 1W6×10 sec. Misslingt der zweite, verliert er durch das Gift 2W6 Lebens- und Ausdauerpunkte. Eine Dschungelwand wird von einer direkt anschließenden Feuerwand und ähnlichen großflächigen Feuerzaubern verbrannt. Dies dauert 2 min, und alle Lebewesen in 6 m Umkreis müssen einen Prüfwurf gegen Gift machen, bei dessen Scheitern sie 1W6 Lebens- und Ausdauerpunkte durch Qualm und giftige Dämpfe verlieren."},
        { type: "Zauber",gruppe: "E", art: "Gestenzauber der Stufe 7", agens:"Verändern: Metall • Erde", ap:"4", zd:"20 sec", reichweite:"Berührung", ziel:"Körper", bereich:"1 Wesen", dauer:"2 min", ursprung:"dämonisch", text: "Eisenhaut", beschreibung:"Der Verzauberte erhält eine eisenharte Haut, die seine Bewegungsweite um 12 und seine Gewandtheit um 40 senkt (Minimalwerte B3 und Gw 10). Die Eisenhaut schützt gegen schwere Treffer genauso wie eine Vollrüstung: Von Lebenspunktverlusten werden 5 LP aufgefangen. Da das Kämpfen in Eisenhaut nicht so anstrengend ist wie in einer Rüstung, verringern sich die Ausdauerverluste, die der Verzauberte durch leichte Treffer hinnehmen muss, ebenfalls um 5 AP. Schwere Treffer verursachen volle AP-Verluste.\n
Mit Eisenhaut können nur Abenteurer verzaubert werden, die keine Metallrüstung tragen. Eine nichtmetallische Rüstung hat für die Dauer des Zaubers keine zusätzliche Schutzwirkung. Solange der Spruch wirkt, wird der Verzauberte auch gegenüber Zauberei wie der Träger von Vollrüstung behandelt. Insbesondere kann er selbst nur eingeschränkt zaubern. Da Eisenhaut die Hautatmung behindert, müssen mindestens 10 min vergehen, bevor der Zauber ein zweites Mal auf dieselbe Person angewandt wird; andernfalls verliert sie 1W6 LP & AP."},
        { type: "Zauber",gruppe: "E", art: "Gestenzauber der Stufe 3", agens:"Erschaffen: Eis • Eis", ap:"1 je m2", zd:"10 sec", reichweite:"50m", ziel:"Umgebung", bereich:"bis zu 10 m2", dauer:"1 min", ursprung:"elementar", text: "Eisiger Nebel" , beschreibung:"Der Wirkungsbereich, der eine zusammenhängende Fläche bilden muss, wird bis in 3 m Höhe mit einer Wolke feiner Eiskristalle bedeckt. Lebewesen verlieren 1W6+2 AP und 1 LP je Runde, die sie sich in der Wolke aufhalten. Rüstung schützt nicht vor dieser Kälte. Feuerkreaturen erleiden doppelten Schaden, und auch Pflanzen zeigen oberflächliche Frostschäden. Geschöpfe, die wie Geister, Untote oder Golems keine Körperwärme besitzen, sind immun gegen den Spruch"},
        { type: "Zauber",gruppe: "E", art: "Gestenzauber der Stufe 4", agens:"Erschaffen: Eis • Eis", ap:"1 je m Breite", zd:"10 sec", reichweite:"15 m", ziel:"Umgebung", bereich:"-", dauer:"10 min", ursprung:"elementar", text: "Eiswand" , beschreibung:"Dieser Spruch lässt in bis zu 15 m Entfernung vom Zauberer eine ca. 50 cm dicke, unbewegliche Wand aus Eis entstehen.\n
Sie reicht vom Boden bis zur Decke eines Raumes, maximal aber bis in eine Höhe von 6 m. Die Breite richtet sich nach der Zahl der aufgewandten Ausdauerpunkte. Das Eis wächst langsam genug aus dem Boden empor, dass Wesen sich ohne Mühe rechtzeitig aus dem betroffenen Bereich entfernen können. Der Zauberer kann die Eiswand auch vor Ende der Wirkungsdauer verschwinden lassen, wenn er dies will.\n
Das Eis der magischen Wand ist durchscheinend, trübt aber die Sicht, so dass Zauberer einen Abzug von –4 auf ihre EW:Zaubern erhalten, wenn sie ein Ziel hinter der Wand anvisieren.\n
Die Eiswand lässt sich wie eine Tür mit schweren Schlagwerkzeugen einschlagen. Um ein für Menschen passierbares Loch zu schaffen, muss man der Wand 50 Punkte Schaden zufügen. Sehr starke Gewalten können eine Eiswand auch in kurzer Zeit zersplittern lassen (Spielleiterentscheidung). Explosionsartig wirkende Zauber wie Feuerkugel, Feuerlanze oder Dämonenfeuer zerschmettern mit 30% auf einen Schlag ein 3m×3m großes Stück einer Eiswand. Wird eine Feuerwand direkt vor eine Eiswand gezaubert, entscheidet ein Zauberduell, welche der beiden bestehen bleibt und welche ausgelöscht wird."},
        { type: "Zauber",gruppe: "E", art: "Gestenzauber der Stufe 5", agens:"Formen: Wasser • Eis", ap:"3", zd:"10 sec", reichweite:"200m", ziel:"Umgebung", bereich:"bis zu 10 m3", dauer:"variabel", ursprung:"elementar", text: "Eiswandlung" , beschreibung:"Der Zauberer kann bis zu 10 Kubikmeter Eis schmelzen lassen. Er kann so zum Beispiel eine 2 m breite und 50 m lange Fahrrinne in der 10 cm dicken Eisschicht auf einem zugefrorenen Fluss schaffen oder einen 50 cm dicken Eispanzer vor einem 4 m breiten und 5 m hohen Tor schmelzen. Die Wirkung des Zaubers hält so lange an, bis das Wasser von allein wieder friert, mindestens aber eine Stunde. Mit Eiswandlung lässt sich auch magisches Eis, z.B. ein Opfer von Vereisen, auftauen, wenn ein Zauberduell gelingt. Der Zauber ist jedoch gegen die belebten Eiskörper von Elementarwesen wirkungslos."},
        { type: "Zauber",gruppe: "E", art: "
Gestenzauber der Stufe 5", agens:"Formen: Ausgangselement • Zielelement", ap:"6", zd:"variabel", reichweite:"5 m", ziel:"Umgebung", bereich:"bis zu 1 m2", dauer:"unendlich", ursprung:"elementar", text: "Elementenwandlung" , beschreibung:"Mit diesem Spruch kann der Zauberer bis zu einen Kubikmeter der Elemente Erde, Wasser, Feuer und Luft ineinander verwandeln. Die größte Dimension (Höhe, Breite, Länge) des Wirkungsbereichs darf dabei höchstens das Vierfache der kleinsten Dimension betragen. Ein Volumen von 2m×1m×0,5m ist gerade noch zulässig. Der verzauberte Bereich muss ganz aus einem Element bestehen. Insbesondere kann man Luft nicht verzaubern, wenn sich im Wirkungsbereich irgendein Objekt befindet. Der Zauber wirkt nicht auf künstlich bearbeitete Steine oder Erde und auch nicht auf die belebten Körper von Elementarwesen. Soll ein magisches oder magisch geschütztes Element umgewandelt werden, entscheidet ein Zauberduell, ob der Zauberer über den Schöpfer dieser Materie obsiegt. Der zum Zaubern nötige Edelstein richtet sich nach dem Zielelement:\n
Verwandlung in Erde
Verwandlung in Feuer
Verwandlung in Wasser
Verwandlung in Luft\n
Die Zauberdauer hängt vom schwersten der an der Umwandlung beteiligten Elemente ab. Ist Erde Ausgangs- oder Zielzustand, dauert der Zaubervorgang 10 min. Ist Wasser, nicht aber Erde beteiligt, beträgt die Zauberdauer 1 min. Die Umwandlung von Feuer in Luft und umgekehrt dauert 10 sec. Durch Elementenwandlung erzeugtes Feuer brennt 10 min, wenn kein Vorrat an brennbarem Material vorhanden ist."},
        { type: "Zauber",gruppe: "E", art: "Wortzauber der Stufe 4", agens:"Zerstören: Magan • Eis", ap:"2", zd:"30 sec", reichweite:"3 m", ziel:"Umgebung", bereich:"1 Objekt", dauer:"0", ursprung:"druidisch", text: "Entgiften" , beschreibung:"Mit dem Spruch kann der Zauberer dafür sorgen, dass Gift auf Gegenständen oder in Getränken und Speisen neutralisiert wird und keinen Schaden mehr anrichten kann. Er muss dabei genau angegeben, wo er das Gift vermutet, z.B. „an diesem grünlich schimmernden Dorn am Schloss der Truhe“ oder „in der fettigen Bratentunke“, nicht aber „ich will diese Truhe - oder das Essen auf meinem Teller - entgiften.“ Der Zauber wirkt nicht gegen Gifte in lebenden Körpern, also weder gegen natürliche Gifte von Tieren und Pflanzen, noch gegen Gifte im Körper eines Opfers."},
        { type: "Zauber",gruppe: "E", art: "Gestenzauber der Stufe 9", agens:"Bewegen: Erde • Erde", ap:"6", zd:"1 min", reichweite:"0 m", ziel:"Umgebung", bereich:"1 km Umkreis", dauer:"10 min", ursprung:"elementar", text: "Erdbeben" , beschreibung:"Der Zauberer stampft rhythmisch auf den Boden und bringt die Erde zum Beben. Er muss hierbei auf natürlichem Erdboden oder Fels stehen. Im Wirkungsbereich können sich alle Wesen mit Ausnahme des Zauberers, der im Einklang mit den Schwingungen des Bodens dahinschreitet, nur mit einem Viertel ihrer Bewegungsweite fortbewegen und müssen jede Runde einen PW:Gewandtheit machen. Misslingt der Wurf, fällt der Betreffende hin und verliert 1W6 AP. Das Erdbeben, das vergleichsweise schwach ist, verursacht normalerweise keinen Schaden an Gebäuden, es sei denn, der Spielleiter entscheidet, dass die betreffende Struktur besonders instabil oder baufällig ist. Im Innern von Gebäuden können Gegenstände von Regalen oder Tischen fallen."},
        { type: "Zauber",gruppe: "E", art: "Gestenzauber der Stufe 5", agens:"Bewegen: Erde • Erde", ap:"3", zd:"Augenblick", reichweite:"50 m", ziel:"Umgebung", bereich:"1 m Umkreis", dauer:"2 min", ursprung:"elementar", text: "Erdfessel" , beschreibung:"Die Erdfessel kann sich nur aus Erde, Sand oder Schlamm bilden. Der Boden wächst im Wirkungsbereich blitzschnell empor und umschließt die Beine eines Wesens, das sich an dieser Stelle befindet, mit einer zähen Erdmasse; gelingt sein WW:Abwehr, kann es dem Zugriff entgehen. Die Erdfessel verhindert jede Fortbewegung und schränkt die Ausweichmöglichkeiten im Kampf so ein, dass der Festgehaltene einen Abzug von –2 auf WW:Abwehr erhält. Das Opfer einer Erdfessel kann einmal versuchen, sich mit einem Kraftakt loszureißen; misslingt der Wurf, ist es zu schwach und muss das Ende der Wirkungsdauer abwarten. Läuft ein zweibeiniges Opfer schnell (mit mehr als B/2), während die Erdfessel es packt, fällt es auf seinen Hosenboden, wenn ihm ein PW:Gewandtheit misslingt. Einmal hingefallen, muss zum Aufstehen wieder ein PW:Gewandtheit gelingen, solange die Beine in der Erdfessel stecken. Wird ein schnell laufendes Pferd verzaubert, stürzt es als Vierbeiner nicht, aber seinem Reiter muss ein EW:Reiten gelingen, wenn er sich im Sattel halten will."},
        { type: "Zauber",gruppe: "E", art: "Gestenzauber der Stufe 9", agens:"Formen: Erde • Erde", ap:"6", zd:"20 sec", reichweite:"Berührung", ziel:"Umgebung", bereich:"1 m3", dauer:"unendlich", ursprung:"elementar", text: "Erdwandlung" , beschreibung:"Der Zauberer kann einen Kubikmeter Erde in Felsen bzw. Felsen in Erde umwandeln. Die größte Dimension (Höhe, Breite oder Länge) des Wirkungsbereichs darf dabei höchstens das Vierfache der kleinsten Dimension betragen. Im Übrigen gelten dieselben Regeln wie für Elementenwandlung mit der einen Ausnahme, dass auch künstlich bearbeitete Erde oder Steine verzaubert werden können. Will der Zauberer magisches oder magisch geschütztes Material umwandeln, muss er ein Zauberduell führen. Wird mit Erdwandlung ein Mauerteil eines Gebäudes in Erde verwandelt, stürzt es im Normalfall nicht sofort ein. Die Erde ist so dicht gepackt, dass sie dem Bau noch genügend Stabilität verleiht."},
        { type: "Zauber",gruppe: "E", art: "Gedankenzauber der Stufe 1", agens:"Erkennen: Magan • Wasser", ap:"1", zd:"Augenblick", reichweite:"0 m", ziel:"Geist", bereich:"15 m Kegel", dauer:"1 min", ursprung:"dämonisch", text: "Erkennen von Leben" , beschreibung:"Befinden sich im Wirkungsbereich des Zaubers Lebewesen, spürt der Zauberer die Anwesenheit ihrer Anima als leichten Druck auf seine Schläfen. Mehr als 30 cm dicke Wände und noch so dünne Metallschichten schirmen die Ausstrahlung ab. Der Zauberer erhält keine Informationen über Art und Anzahl der Lebewesen, kann aber ihre Entfernung bis auf 2 m genau spüren. Die Magie von Erkennen von Leben spricht auf das Vorhandensein einer ausgeprägten Anima an. Daher reagiert der Zauber - im scheinbaren Widerspruch zu seinem Namen - auch auf die Anwesenheit von Geistern, nicht aber auf Untote, Golems oder Automaten."},
        { type: "Zauber",gruppe: "E", art: "Gedankenzauber der Stufe 4", agens:"Erkennen: Magan • Magan", ap:"2", zd:"Augenblick", reichweite:"15 m", ziel:"Geist", bereich:"1 m2", dauer:"0", ursprung:"dämonisch", text: "Erkennen von Zauberei" , beschreibung:"Befinden sich im Wirkungsbereich magische Gegenstände, verzauberte, heraufbeschworene oder von Natur aus magische Wesen, verspürt der Zauberer ein angenehmes Wärmegefühl. Er erhält aber keine Informationen, worauf sein Zauber anspricht. Jedes Objekt oder Wesen im Wirkungsbereich kann die Quelle der magischen Ausstrahlung sein. Erkennen von Zauberei reagiert auf Anomalien in der Verteilung der Essentia Magan, wie sie durch die arkanen Kräfte normaler Zaubersprüche und durch entsprechende Wundertaten der Priester erzeugt werden. Mit dem Spruch lassen sich daher Verzauberungen durch Dweomer, Bardenlieder oder Namensmagie nicht entdecken."},
        { type: "Zauber",gruppe: "E", art: "Gestenzauber der Stufe 10", agens:"Beherrschen: Magan • Feuer", ap:"6", zd:"20 sec", reichweite:"30 m", ziel:"Geist", bereich:"3 m Umkreis", dauer:"2 min, k", ursprung:"dämonisch", text: "Erscheinungen" , beschreibung:"Der Zauberer kann mit diesem Spruch nach Belieben Illusionen erzeugen, die sich auch bewegen können. Die Erscheinungen können aus mehreren, sich unabhängig voneinander bewegenden Gegenständen oder Wesen bestehen. Sie müssen aber stets alle in den beweglichen Wirkungsbereich passen und dürfen nicht höher als 3 m sein. Das Zentrum des Wirkungsbereichs darf sich nicht weiter als die Reichweite von dem Schöpfer der Illusionen entfernen. Der Zauberer muss sich während der ganzen Wirkungsdauer auf seinen Zauber konzentrieren. Die Magie dieser Illusion beeinflusst normalerweise nur das, was die Opfer zu sehen glauben. Für jeweils zusätzliche 6 AP kann der Zauberer aber auch Geräusche bzw. Geruch und Geschmack vortäuschen."},
        { type: "Zauber",gruppe: "E", art: "Gestenzauber der Stufe 5", agens:"Verändern: Eis • Erde", ap:"3", zd:"10 sec", reichweite:"30 m", ziel:"Körper", bereich:"1 Wesen", dauer:"2 min", ursprung:"schwarzmagisch", text: "Erwecken" , beschreibung:"Der Zauber muss innerhalb von 1 min nach dem Tod eines Lebewesens auf den Leichnam angewandt werden. Bei Erfolg erhebt er sich und greift auf Seiten des Zauberers für kurze Zeit noch einmal als Zombie in den Kampf ein. Nach Ablauf der Wirkungsdauer bricht das Wesen endgültig tot zusammen. Die Spieldaten des Zombies hängen von der Art des erweckten Wesens ab. Für menschenähnliche Opfer gelten die Standardwerte:\n
Zombie (Grad 2)
9 LP, ∞ AP - TR - St 90, Gw 30, In t20, B 18\n
Angriff: Klaue+5 (1W6+1) oder Waffe+5 (+2 auf Schaden), Raufen+6 (1W6–2) - A􏰃􏰄􏰅􏰆􏰁+12, R􏰅􏰇􏰈􏰇􏰉􏰅􏰊􏰋+11/13"},
        { type: "Zauber", gruppe: "F", art: "Gestenzauber der Stufe 2", agens:"Verändern: Erde • Erde", ap:"1", zd:"10 sec", reichweite:"Berührung", ziel:"Körper", bereich:"1 Wesen", dauer:"2 min", ursprung:"elementar", text: "Felsenfaust" , beschreibung:"Die Person, die verzaubert werden soll, muss während der Zauberdauer einen Kieselstein in der zur Faust geballten rechten oder linken Hand halten. Gelingt der Spruch, wird die Faust kurzzeitig zu massivem Fels. Der Verzauberte kann mit ihr im Kampf zuschlagen oder Gegenstände zertrümmern. Im Nahkampf trifft er mit seinem Fertigkeitswert für Angriffe mit der Hand oder mit Faustkampf. Er richtet dabei 1W6 Schaden an, wozu der persönliche Schadensbonus addiert wird. Im Handgemenge bringt die Felsenfaust keine Vorteile, da der Kämpfer hier nicht ausholen und die Wucht seiner Schläge ausnutzen kann. Die veränderte Faust ist starr und unbeweglich, so dass man mit ihr nichts greifen und auch keine anderen Handlungen ausführen kann. Unter anderem kann ein Zauberer, der diesen Spruch auf sich selbst anwendet, während der Wirkungsdauer keine Gestenzauber anwenden. Die Felsenfaust hat eine eigene arkane Ausstrahlung, so dass sie als schwere magische Waffe*(+0/+0) zählt und übernatürliche Gegner mit ihr bekämpft werden können, z.B. auch Golems."},
        { type: "Zauber", gruppe: "F", art: "Gestenzauber der Stufe 6", agens:"Erschaffen: Luft • Magan", ap:"2 je Grad", zd:"10 sec", reichweite:"30 m", ziel:"Körper", bereich:"1 Wesen", dauer:"10 min, k", ursprung:"göttlich", text: "Fesselbann" , beschreibung:"Der Zauberer erzeugt ein Netz aus transparenten, schwach golden leuchtenden Fäden magischer Energie, das den Körper des Opfers eng umschließt. Es kann seine Gliedmaßen nicht mehr bewegen, ist aber noch in der Lage, um Hilfe zu rufen oder wild um sich zu beißen. Das Opfer kann einmal versuchen, das magische Netz mit einem Kraftakt zu zerreißen. Gelingt ihm dies, lösen sich die Fäden arkaner Energie in Nichts auf. Der Zauberer muss sich die ganze Zeit über auf den Spruch konzentrieren, wenn die Wirkung nicht vorzeitig enden soll."},
        { type: "Zauber", gruppe: "F", art: "Gestenzauber der Stufe 1", agens:"Erschaffen: Feuer • Feuer", ap:"1", zd:"Augenblick", reichweite:"0 m", ziel:"Umgebung", bereich:"Zauberer", dauer:"2 min, k", ursprung:"elementar", text: "Feuerfinger" , beschreibung:"Aus einem Finger des Zauberers entspringt eine kleine Flamme, mit der er Kerzen, Brennholz oder Fackeln entzünden kann. Die Flamme spendet außerdem Licht wie eine Kerze. Der Feuerfinger erlischt vorzeitig, wenn der Zauberer sich nicht mehr konzentriert."},
        { type: "Zauber", gruppe: "F", art: "Gestenzauber der Stufe 3", agens:"Erschaffen: Feuer • Feuer", ap:"2", zd:"10 sec", reichweite:"50 m", ziel:"Umgebung", bereich:"3 m Umkreis", dauer:"2 min, k", ursprung:"elementar", text: "Feuerkugel" , beschreibung:"Der Zauberer erzeugt in etwa einem Meter Entfernung eine in der Luft schwebende feurige Kugel. Er kann sie mit seiner Willenskraft um 3 m pro 10 sec bewegen, solange sie sich innerhalb der Reichweite befindet und er sich konzentriert. Sind diese beiden Bedingungen nicht mehr erfüllt oder endet die Wirkungsdauer, explodiert die Feuerkugel.\n
Die Explosion fügt Wesen in 3 m Abstand 1W6 schweren Schaden zu. Für jeden Meter, den jemand sich näher am Explosionszentrum befindet, erhöht sich der Schaden um weitere 1W6, bis er direkt am Ort der Kugel 4W6 beträgt. Der Schaden wird von außen nach innen ausgewürfelt. Dabei wird jeweils das Ergebnis eines weiteren Würfelwurfs addiert. Rüstung schützt gegen die LP-Verluste. Wesen, deren WW:Abwehr gelingt, erleiden die Hälfte an leichtem Schaden. Feuerempfindliche Kreaturen erleiden doppelten Schaden durch die Feuerkugel, aber selbst unintelligente Wesen versuchen, ihr auszuweichen.\n
Explodiert die Feuerkugel direkt vor einer Holztür, richtet sie dort 3W6 Schaden an. Leicht entzündliche Gegenstände wie Papier, Stroh, dürre Äste oder dünne Vorhänge im Explosionsbereich fangen an zu brennen. Schwere Stoffe und massives Holz werden nur oberflächlich versengt. Menschen erleiden keinen zusätzlichen Schaden, wenn sie leichte und brennbare Kleidung tragen; dies ist in den oben erwähnten Werten bereits berücksichtigt."},
        { type: "Zauber", gruppe: "F", art: "Gestenzauber der Stufe 6", agens:"Erschaffen: Feuer • Feuer", ap:"3", zd:"10 sec", reichweite:"50 m", ziel:"Umgebung", bereich:"Strahl", dauer:"0", ursprung:"elementar", text: "Feuerlanze" , beschreibung:"Der Zauberer erzeugt einen etwa 1 m langen Speer aus Feuer, der geradlinig auf das Ziel zufliegt. Gelingt der WW:Abwehr des Opfers, verliert es nur 1W6–2 AP. Andernfalls trifft die Feuerlanze voll auf dem Körper auf und vergeht in einer feurigen Explosion, die 2W6 schweren Schaden anrichtet und leicht entzündlichen Besitz des Opfers entflammt. Feuerempfindliche Wesen erleiden doppelten Schaden. Rüstung verringert wie bei einer Feuerkugel (s. S. 81) die Lebenspunktverluste durch die Feuerlanze, da der Schaden hauptsächlich durch die Explosion und weniger durch die Hitzeentwicklungangerichtet wird. Wird die Feuerlanze gegen eine Holztür oder ein ähnliches unbewegliches Hindernis gerichtet, trifft sie automatisch und richtet 2W6 Schaden an. Durch die Wucht der Explosion werden daher auch Steinsäulen und Gegenstände aus anderen, nicht brennbaren Materialien beschädigt."},
        { type: "Zauber", gruppe: "F", art: "Gedankenzauber der Stufe 5", agens:"Verändern: Feuer • Feuer", ap:"3", zd:"10 sec", reichweite:"Berührung", ziel:"Körper", bereich:"1 Wesen", dauer:"10 min", ursprung:"elementar", text: "Feuerlauf" , beschreibung:"Der Zauberer macht ein Lebewesen gegen normale Feuer und gegen vergleichbare Hitze unempfindlich, indem er den äußeren Hautschichten eine feuerfeste Struktur gibt. Der Verzauberte kann dann unbeschadet über glühende Kohlen laufen oder seine Hand in kochendes Wasser halten. Kleidung und andere brennbare Ausrüstung behalten ihre normale Feuerempfindlichkeit. Besonders heiße Feuer (Lava, weißglühendes Metall, Zauberölfeuer) oder magische Feuer (Feuerkugel, Drachenhauch usw.) richten nur halb so viel Schaden (aufgerundet) wie üblich an."},
        { type: "Zauber", gruppe: "", art: "Gestenzauber der Stufe 9", agens:"Formen: Feuer • Feuer", ap:"6", zd:"20 sec", reichweite:"30 m", ziel:"Umgebung", bereich:"2 m Umkreis", dauer:"2 min", ursprung:"elementar", text: "Feuermeisterschaft" , beschreibung:"Der Zauberer kann einen kleinen Funken innerhalb weniger Augenblicke zu einem größeren Feuer wachsen lassen, das den ganzen Wirkungsbereich bedeckt, ohne Brennstoff zu benötigen. Leicht entzündliches Material (trockenes Holz, Pergament, Öl usw.) fängt Feuer und brennt auch nach Ende der Spruchwirkung weiter. Da die Flammen nur etwa kniehoch sind, erleiden Personen, die den Wirkungsbereich durchqueren oder sich darin aufhalten, nur 1W6–1 schweren Schaden pro Runde. Entsteht das Feuer am Aufenthaltsort einer Kreatur, kann sie aus dem betroffenen Bereich herausspringen, ohne Schaden zu erleiden, wenn ihr WW:Abwehr gelingt. Geister und Feuerelementarwesen sind immun gegen dieses magisch vergrößerte normale Feuer. Umgekehrt kann der Zauberer mit Feuermeisterschaft auch alle normalen Feuer im Wirkungsbereich augenblicklich löschen; ausgenommen sind nur magische Flammen und extrem heiße Feuerquellen (Zauberöl, Lava usw.)."},
        { type: "Zauber", gruppe: "", art: "Gestenzauber der der Stufe 12", agens:"Erschaffen: Feuer • Feuer", ap:"18", zd:"30 sec", reichweite:"100 m", ziel:"Umgebung", bereich:"30 m Umkreis", dauer:"1 min, k", ursprung:"elementar", text: "Feuerregen" , beschreibung:"Der Spruch kann nur unter freiem Himmel ausgeführt werden. Im Wirkungsbereich, einem Kreis von 60 m Durchmesser mit bis zu 100 m vom Zauberer entferntem Zentrum, geht ein Regen aus heißen, etwa faustgroßen Flämmchen nieder. Der Zauberer muss sich ständig auf den Feuerregen konzentrieren, wenn er nicht vorzeitig enden soll. Jede Spielfigur im Wirkungsbereich wird einmal pro Runde mit Erfolgswert+15 angegriffen. Bei einem Treffer erleidet sie durch die Flammen 2W6 Schaden. Leichter Schaden wird durch anstrengende Ausweichmanöver, durch die kräftezehrende Hitze und die Rauchentwicklung verursacht, während es sich bei schwerem Schaden um Brandwunden handelt. Rüstung verringert die durch den Feuerregen verursachten LP- Verluste. Mit einem großen Schild oder mit einem ähnlichen schirmartigen Schutz erhält ein Abenteurer zusätzlich +4 auf seinen WW:Abwehr."},
        { type: "Zauber", gruppe: "", art: "Gestenzauber der Stufe 8", agens:"Erschaffen: Feuer • Feuer", ap:"4", zd:"20 sec", reichweite:"0 m", ziel:"Umgebung", bereich:"6 m Umkreis", dauer:"30 min", ursprung:"elementar", text: "Feuerring" , beschreibung:"Der Zauberer erschafft einen 12 m durchmessenden Kreis aus 6 m hohen Flammen um sich herum. Das Feuer wirkt in jeder Hinsicht wie eine Feuerwand. Die Flammen wachsen langsam genug empor, dass Personen auf dem Kreisrand rechtzeitig beiseitetreten können, ohne in das Feuer zu geraten. Der Ring bewegt sich nicht, und der Zauberer muss während der Wirkungsdauer im Zentrum verharren, braucht sich aber nicht zu konzentrieren. Wendet der Zauberer Feuerring im Innern eines Gebäudes an, reichen die Flammen nur bis zur Raumdecke; besteht sie aus Holz, fängt sie je nach Festigkeit und Stabilität durch die aufsteigende Hitze nach 10-20 min an zu brennen. Der Feuerring versucht, den größtmöglichen Umfang anzunehmen, kann aber Hindernisse wie Wände und geschlossene Türen nicht überwinden. In einem abgeschlossenen Zimmer verläuft das Feuer entlang der Wände."},
        { type: "Zauber", gruppe: "", art: "Gestenzauber der Stufe 6", agens:"Erschaffen: Eis • Eis", ap:"3", zd:"10 sec", reichweite:"15 m", ziel:"Umgebung", bereich:"-", dauer:"2 min", ursprung:"elementar", text: "Feuerschild" , beschreibung:"Der Zauberer errichtet einen 2 m hohen und 2 m breiten Schutzschild gegen Feuer. Das Kraftfeld ist mit der magischen Energie des Elements Eis aufgeladen. Es ist zwar durchsichtig, kann aber bei genauem Hinschauen an einem silbrig-weißen Schimmern der Luft erkannt werden. Normales Feuer und seine Hitzestrahlung kann den Feuerschild nicht durchdringen und sich nur seitlich oder oberhalb der schützenden Fläche ausbreiten. Magisches Feuer wie zum Beispiel eine Feuerlanze oder der Hauch eines Drachen wird von dem Schutzschild bis zu einer Gesamthöhe von 30 Schadenspunkten absorbiert. Ist diese Grenze erreicht, bricht der Feuerschild zusammen.\n
Feuerelementarwesen meiden den Schutzschild; werden sie mit Gewalt hineingedrängt, erleiden sie 4W6 schweren Schaden. Der Feuerschild wird hierbei wie durch magisches Feuer geschwächt: die geraubten AP werden wie absorbierte Schadenspunkte angerechnet. Andere Geschöpfe können das magische Feld ungehindert passieren."},
        { type: "Zauber", gruppe: "", art: "Gestenzauber der Stufe 4", agens:"Erschaffen: Feuer • Feuer", ap:"1 je m Breite", zd:"10 sec", reichweite:"15 m", ziel:"Umgebung", bereich:"-", dauer:"10 min", ursprung:"elementar", text: "Feuerwand" , beschreibung:"Der Zauberer erschafft eine ca. 1 m dicke, unbewegliche magische Wand aus hoch auflodernden Flammen. Sie reicht vom Boden bis zur Decke eines Raumes, maximal aber bis in eine Höhe von 6 m. Die Flammen wachsen langsam genug empor, dass Wesen sich mühelos aus dem Bereich entfernen können. Der Zauberer kann die Feuerwand auch vor Ende der Wirkungsdauer verschwinden lassen, wenn er dies will.\n
Jedes stoffliche Wesen, das diese Feuerwand durchqueren will, erleidet dabei 2W6 schweren Schaden (feuerempfindliche Geschöpfe 4W6). Trotz seiner Größe strahlt das Feuer zur Seite hin kaum Hitze aus, so dass nur direkt angrenzende brennbare Materialien entflammt werden - zum Beispiel eine Dschungelwand, ein Wandbehang oder eine dürre Hecke. Das Holz von Türen oder der Stamm eines Baumes sind dagegen zu massiv, um innerhalb der begrenzten Wirkungsdauer mehr als nur etwas angekohlt zu werden. Eine Feuerwand vermag keine Geschosse oder Zauber aufzuhalten; da sie die Sicht beeinträchtigt, erhalten Schützen und Zauberer aber Abzüge von –4 auf ihre Erfolgswürfe. Wird eine Eiswand direkt vor eine Feuerwand gezaubert, so entscheidet ein Zauberduell, welche der beiden bestehen bleibt und welche ausgelöscht wird."},
        { type: "Zauber", gruppe: "", art: "Gestenzauber der Stufe 3", agens:"Erschaffen: Feuer • Feuer", ap:"2", zd:"10 sec", reichweite:"0 m", ziel:"Umgebung", bereich:"Zauberer", dauer:"2 min", ursprung:"elementar", text: "Flammende Hand" , beschreibung:"Der Zauberer lässt in seiner Hand Feuer vom Umfang einer Fackelflamme entstehen. Er selbst ist vor Verbrennungen geschützt, muss aber darauf achten, seine Kleidung nicht versehentlich anzuzünden. Der Zauberer kann mit der Flamme spielen, z.B. sie grob formen, verschwinden und wieder erscheinen lassen, sie zerteilen und mit den Bruchstücken jonglieren, ja sogar Feuer spucken. Er kann mit der entflammten Hand im Nahkampf angreifen (mit seinem Fertigkeitswert für Angriffe mit der Hand) und dabei den Schaden einer Fackel anrichten (1W6–2; gegen feuerempfindliche Wesen 2W6). Er kann die Flamme auch einmal als improvisiertes Wurfgeschoss wie eine Fackel auf ein Ziel schleudern."},
        { type: "Zauber", gruppe: "", art: "Gestenzauber der Stufe 6", agens:"Formen: Feuer • Metall", ap:"4", zd:"1 min", reichweite:"Berührung", ziel:"Umgebung", bereich:"1 Objekt", dauer:"10 min", ursprung:"elementar", text: "Flammenklinge" , beschreibung:"Der Zauberer kann eine Waffe mit einer Klinge aus Alchimistenmetall verzaubern (Schwert oder Stichwaffe). An dieser Klinge züngeln heiße Flammen entlang, die bei Treffern zusätzlich 2 Punkte Schaden anrichten (bei feuerempfindlichen Wesen zusätzlich 1W6+2 Punkte). Mit der Flammenklinge kann man alle übernatürlichen Wesen bekämpfen, die sonst nur von magischen Waffen mit einem Bonus von wenigstens +2 auf Angriff oder Schaden verletzt werden können. Das magische Feuer leuchtet wie eine Fackel und kann auch benutzt werden, um Brennbares zu entzünden. Statt einer Waffe aus Alchimistenmetall kann man auch ein magisches Schwert oder einen magischen Dolch mit Flammenklinge verzaubern."},
        { type: "Zauber", gruppe: "", art: "Gestenzauber der Stufe 2", agens:"Erschaffen: Holz • Holz", ap:"1", zd:"Augenblick", reichweite:"Berührung", ziel:"Umgebung", bereich:"1 Wesen", dauer:"2 min", ursprung:"druidisch", text: "Flammenkreis" , beschreibung:"Der Verzauberte wird von einer kalten, blaugrünen Flammenlohe aus konzentrierter Lebenskraft eingehüllt, die ihn vor Untoten, Geisterwesen und vor nebelartigen Todeszaubern (mit dem Agens Eis) wie zum Beispiel Eisiger Nebel, Hauch der Verwesung oder Todeshauch schützt. Untote können mit mindestens 50 cm langen Waffen, mit Fernwaffen oder mit Zauberei gegen den Geschützten kämpfen, dürfen aber selbst nicht mit den Flammen in Berührung kommen. Geisterwesen stehen nur magische Angriffe zur Verfügung. Ein Untoter oder Geist, der unfreiwillig die Flammen berührt, erleidet keinen Schaden, weicht aber mit abgrundtiefem Unbehagen zurück."},
        { type: "Zauber", gruppe: "", art: "Gestenzauber der Stufe 5", agens:"Erschaffen: Feuer • Feuer", ap:"1 je m2", zd:"10 sec", reichweite:"50 m", ziel:"Umgebung", bereich:"bis zu 10 m2", dauer:"1 min", ursprung:"elementar", text: "Flammenteppich" , beschreibung:"Im Wirkungsbereich, der eine zusammenhängende Fläche bilden muss, züngeln knöchelhohe magische Flammen empor. Stoffliche Wesen verlieren 1W3 LP und AP je Runde, die sie sich auf der brennenden Fläche aufhalten. Das Durchqueren des Flammenteppichs verursacht ebenfalls 1W3 schweren Schaden. Wem es gelingt, über den brennenden Bereich hinweg zu springen, erleidet keinen Schaden. Feuerempfindliche Kreaturen erleiden doppelten Schaden."},
        { type: "Zauber", gruppe: "", art: "Gestenzauber der Stufe 1", agens:"Formen: Magan • Metall", ap:"1", zd:"10 sec", reichweite:"Berührung", ziel:"Umgebung", bereich:"1 Objekt", dauer:"10 min", ursprung:"druidisch", text: "Flicken" , beschreibung:"Der Zauber kann kleine Gegenstände flicken, was aber nicht lange hält. Nach Ende der Wirkungsdauer sind sie wieder in demselben Zustand wie vor der magischen Reparatur. Flicken wirkt nur auf Schadstellen, die in einen Würfel mit 10 cm Kantenlänge passen. Beispiele sind ein zerbrochener Schlüssel, ein kleiner Riss in einem Hemd, eine gesprungene Tasse, eine zerbrochene Dolchklinge oder ein zerschnittenes Seil. Zerstörte magische Gegenstände erhalten durch Flicken nur ihre äußere Form, aber nicht ihre magischen Eigenschaften zurück."},
        { type: "Zauber", gruppe: "", art: "Gestenzauber der Stufe 11", agens:"Bewegen: Luft • Erde ", ap:"9", zd:"30 sec", reichweite:"", ziel:"Körper", bereich:"Zauberer", dauer:"1 h, k", ursprung:"dämonisch", text: "Fliegen" , beschreibung:"Mit Hilfe dieses Spruches kann der Zauberer mit B24 fliegen. Er darf dabei höchstens 25 kg an zusätzlichem Gewicht tragen. Während der Wirkungsdauer muss er sich konzentrieren. Wird der Fliegende z.B. mit Fernwaffen schwer getroffen oder wird der Spruch mit Bannen von Zauberwerk vorzeitig beendet, so stürzt er ab und erleidet entsprechenden Schaden."},
        { type: "Zauber", gruppe: "", art: "Gedankenzauber der Stufe 7", agens:"Beherrschen: Wasser • Feuer", ap:"4", zd:"10 sec", reichweite:"500 m", ziel:"Geist", bereich:"1 Wesen", dauer:"30 min, k", ursprung:"dämonisch", text: "Freundesauge" , beschreibung:"Freundesauge nutzt die auf der Ebene der Anima bestehende gefühlsmäßige Bindung zwischen einem Menschen und einer vertrauten Person oder einem vertrauten Tier und führt zu einer magischen Kopplung der Astralleiber. Dadurch kannder Zauberer durch die Augen des anderen Wesens sehen. Verdoppelt (verdreifacht) er die für den Zauber eingesetzten Ausdauerpunkte, kann er zusätzlich auch mithören oder sogar mithören und mitfühlen. Während der Wirkungsdauer muss sich der Zauberer konzentrieren und kann seine eigenen Sinne nicht benutzen; er nimmt nicht wahr, was um ihn selbst herum vorgeht.\n
Der Zauberer und das Wesen, dessen Wahrnehmungsfähigkeiten er nutzt, müssen eng vertraut sein. Menschen und ähnlich intelligente Geschöpfe müssen darüber hinaus einwilligen, dass ein Fremder ihre Sinne mitbenutzt, da sie sich jederzeit von der Wirkung des Spruches befreien können.\n
Der Zauberer muss ähnlich funktionierende Augen wie das verzauberte Wesen haben, da er sonst die auf ihn einströmenden Reize nicht sinnvoll verarbeiten kann. Ein menschenähnlicher Zauberer kann daher den Spruch auf Säugetiere, Vögel, Reptilien, Amphibien oder Fische anwenden, nicht aber auf Spinnen oder Insekten."},
        { type: "Zauber", gruppe: "", art: "Gestenzauber der Stufe 2", agens:"Erschaffen: Eis • Eis", ap:"1", zd:"10 sec", reichweite:"200 m", ziel:"Umgebung", bereich:"Strahl", dauer:"0", ursprung:"elementar", text: "Frostball" , beschreibung:"Während des Rituals hält der Zauberer die Perle aus Silber in seiner Hand und führt eine Schleuderbewegung in Richtung des Ziels aus. Vor allem Schamanen ziehen ein kleines, perlenförmig zurechtgeschliffenes Stück Bergkristall als materielle Komponente vor. Dabei entsteht eine schneeballgroße Kugel aus extrem kalten Eiskristallen, die schnurstracks auf das Opfer zufliegt. Wie bei Blitze schleudern ist kein EW:Angriff nötig. Das Opfer kann aber versuchen, dem Frostball mit einem WW:Abwehr auszuweichen; gelingt der Widerstandswurf, verliert es nur 1 AP. Andernfalls raubt ihm die eisige Kälte 1W6 AP und 2 LP. Rüstung schützt nicht gegen Schaden durch den magischen Frost. Geschöpfe, die wie Geister, Untote oder Golems nicht leben, sind immun gegen den Spruch, während Feuerkreaturen doppelten Schaden erleiden."},
        { type: "Zauber", gruppe: "", art: "", agens:"Beherrschen: Feuer • Feuer", ap:"2 je Grad", zd:"10 sec", reichweite:"30 m", ziel:"Geist", bereich:"1 Wesen", dauer:"1 min", ursprung:"dämonisch", text: "Funkenregen" , beschreibung:"Der optische Sinn des Opfers wird verwirrt, so dass es um sich herum eine Wolke aus wirbelnden, leuchtenden Funken sieht. Es wird orientierungslos und kann mit normaler Geschwindigkeit nur in eine zufällige Richtung laufen. Gezielt kann der Verzauberte sich nur langsam bewegen (B6) und muss dabei auf andere Handlungen verzichten. Im Kampf erleidet er Abzüge von –4 auf Angriff und Abwehr; Fernkampf ist unmöglich, so lange die Sehstörung anhält. Außerdem kann er nur Berührungszauber sowie Zauber, die auf ihn selbst wirken, einsetzen."},
        { type: "Zauber", gruppe: "G", art: "Gestenzauber der Stufe 1", agens:"Erkennen: Magan • Eis", ap:"1", zd:"10 sec", reichweite:"0 m", ziel:"Umgebung", bereich:"100 m Umkreis", dauer:"10 min", ursprung:"dämonisch", text: "Geisterhorn" , beschreibung:"Der Zauber ähnelt dem Dritten Auge. Die materielle Komponente ist eine schlanke, durchsichtige Kristallpyramide von der Größe einer Mohrrübe, die ebenfalls vor der Stirn des Zauberers schwebt. Sie trübt sich ein und wird von schwarzen Schlieren durchzogen, wenn sich Untote oder Geisterwesen im Wirkungsbereich aufhalten. Am Grad der Schwärzung kann der Zauberer abschätzen, wie gefährlich das stärkste der entdeckten Wesen im Vergleich zu bekannten Kreaturen ist. Untote und Geister ab Grad 4 spüren die Ausstrahlung des Geisterhorns, wenn ihnen ein EW:Resistenz gegen Geisteszauber gelingt."},
        { type: "Zauber", gruppe: "G", art: "Gestenzauber der Stufe 6", agens:"Erschaffen: Metall • Metall", ap:"1 je 5 m2 Fläche", zd:"10 sec", reichweite:"Berührung", ziel:"Umgebung", bereich:"bis zu 100 m2", dauer:"8 h", ursprung:"dämonisch", text: "Geistersperre" , beschreibung:"Der Zauberer macht Wände, Türen, Decken und Böden undurchdringlich für körperlose Geisterwesen. Er kann so einen kleinen Raum sichern, oder Geister am Verlassen eines Raumes hindern."},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenfeuer" , beschreibung:""},
        { type: "Zauber", gruppe: "", art: "", agens:": • ", ap:"", zd:"", reichweite:"", ziel:"", bereich:"", dauer:"", ursprung:"", text: "Elfenklinge", beschreibung:"" }

    ]

}
